### ISSUE TITLE
cannot download [graph_matching.json]

### ISSUE THREAD

**Issue by wangjade54241** [HKUDS/GraphGPT#1]
[graph_matching.json](https://huggingface.co/datasets/Jiabin99/graph_matching) 
The above page opens with a 404 error. Please provide a correct url. Thansk.

**Comment by tjb-tech** [comment]
Thank you for your reminder! This is a missing upload and we have uploaded the data at link [graph-matching.json](https://huggingface.co/datasets/Jiabin99/graph-matching). And we have fix this typos in README.md. Thank you again for your attention on our GraphGPT!

**Comment by zhihui-shao** [comment]
Was LLM not fine-tuned at either stage in the paper?
