### ISSUE TITLE
No module named 'fastchat'

### ISSUE THREAD

**Issue by wangjade54241** [HKUDS/GraphGPT#11]
I encountered an error **No module named 'fastchat'**  while running the train_mem.py
some details:
（from fastchat.conversation) in model_adapter.py 

Is the fastchat the folder name of a project ?

**Comment by guspan-tanadi** [comment]
As according to [Environment Preparation](../../GraphGPT#2-environment-preparation--back-to-top) section. Did the fastchat has been installed?
Part of command related as follow.
`pip3 install "fschat[model_worker,webui]"`

**Comment by tjb-tech** [comment]
> I encountered an error **No module named 'fastchat'** while running the train_mem.py some details: （from fastchat.conversation) in model_adapter.py
> 
> Is the fastchat the folder name of a project ?

You can also install fastchat from source using the following script: 
```
git clone https://github.com/lm-sys/FastChat.git
cd FastChat
pip3 install --upgrade pip  # enable PEP 660 support
pip3 install -e ".[model_worker,webui]"
```
