### ISSUE TITLE
where should i put the stage1.sh when i run it

### ISSUE THREAD

**Issue by kunupup** [HKUDS/GraphGPT#12]
bin/python: can't open file 'graphgpt/train/train_mem.py': [Errno 2] No such file or directory

**Comment by kunupup** [comment]
Traceback (most recent call last):
  File "graphgpt/train/train_mem.py", line 4, in <module>
    from graphgpt.train.llama_flash_attn_monkey_patch import (
ModuleNotFoundError: No module named 'graphgpt'
Traceback (most recent call last):

**Comment by smurf-1119** [comment]
i also meet the same problem. Can you tell me how do you solve it?

**Comment by lhkhiem28** [comment]
Hi @kunupup i also meet the same problem. Can you tell me how do you solve it?
