### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory ImportError: ImportErrorlibc10_cuda.so: cannot open shared object file: No such file or directory:  libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kunupup** [HKUDS/GraphGPT#13]
how to solve this error ,do you have any experience of this ,thanks

**Comment by kunupup** [comment]
i reinstall torch ,but there is a new error:
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by tjb-tech** [comment]
> libraries

Thank you for your feedback. Actually it's an error not related to GraphGPT. The original error of ImportError: libc10_cuda.so:  means that the absence of some cuda kernel in your torch. And the new error means that the process of installing bitsandbytes may be wrong. Maybe you can uninstall the bitsandbytes and re-install it.

**Comment by kunupup** [comment]
AttributeError: 'GraphLlamaConfig' object has no attribute 'pretrain_graph_model_path'

**Comment by tjb-tech** [comment]
> AttributeError: 'GraphLlamaConfig' object has no attribute 'pretrain_graph_model_path'

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
Please refer to issue #7.
Hope my answer is help for you. Wishing you an early Merry Christmas!
