### ISSUE TITLE
关于找不到config.json文件

### ISSUE THREAD

**Issue by nulinuli** [HKUDS/GraphGPT#14]
2023-11-09 16:41:33,050	INFO worker.py:1673 -- Started a local Ray instance.
(eval_model pid=11217) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
(eval_model pid=11217) start loading
Traceback (most recent call last):
  File "./run_graphgpt.py", line 240, in <module>
    run_eval(args, args.num_gpus)
  File "./run_graphgpt.py", line 94, in run_eval
    ans_jsons.extend(ray.get(ans_handle))
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::eval_model() (pid=11217, ip=172.27.37.124)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./run_graphgpt.py", line 116, in eval_model
    model = GraphLlamaForCausalLM.from_pretrained(args.model_name, torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True).cuda()
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3085, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/fry/桌面/GraphGPT-main/graphgpt/model/GraphLlama.py", line 284, in __init__
    self.model = GraphLlamaModel(config)
  File "/home/fry/桌面/GraphGPT-main/graphgpt/model/GraphLlama.py", line 104, in __init__
    clip_graph, args= load_model_pretrained(CLIP, config.pretrain_graph_model_path)
  File "/home/fry/桌面/GraphGPT-main/graphgpt/model/GraphLlama.py", line 55, in load_model_pretrained
    assert osp.exists(osp.join(pretrain_model_path, 'config.json')), 'config.json missing'
AssertionError: config.json missing
(eval_model pid=11217) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
(eval_model pid=11217) finish loading
(eval_model pid=11217) start loading
我下载的是您的checkpoints

**Comment by zhuochunli** [comment]
你好，请问解决了吗？我也是在evaluation方面出了问题

**Comment by Longmeix** [comment]
我也遇到了这个问题，请问有人解决了吗

**Comment by daixixiwang** [comment]
这个作者有个小错误，脚本中和实际目录结构下的名字不一致，手动改下就可以了 。

**Comment by xvrrr** [comment]
我也在eval阶段遇到了这个问题，原因是config.json里的graph_tower，pretrain_graph_model_path和clip_gt_arxiv的文件路径指向不一致，通过更改文件路径解决，以下是我在eval阶段使用的config.json 和 clip_gt_arxiv路径：{
  "_name_or_path": "./vicuna-7b-v1.5-16k",
  "architectures": [
    "GraphLlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "freeze_graph_mlp_adapter": false,
  "graph_hidden_size": 128,
  "graph_select_layer": -2,
  "graph_tower": "clip_gt_arxiv_pub",
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "max_sequence_length": 16384,
  "model_type": "GraphLlama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub",
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 4.0,
    "type": "linear"
  },
  "sep_graph_conv_front": false,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.31.0",
  "tune_graph_mlp_adapter": true,
  "use_cache": false,
  "use_graph_proj": true,
  "use_graph_start_end": true,
  "vocab_size": 32003

}

![image](https://github.com/user-attachments/assets/4cd191c4-24c5-4c3e-8d22-a0c01f8993cb)

**Comment by xvrrr** [comment]
> 我也遇到了这个问题，请问有人解决了吗

可以试试这样设置路径

**Comment by Longmeix** [comment]
谢谢你们详细的回答，我后续解决了这个问题

**Comment by CigarOVO** [comment]
> 我也在eval阶段遇到了这个问题，原因是config.json里的graph_tower，pretrain_graph_model_path和clip_gt_arxiv的文件路径指向不一致，通过更改文件路径解决，以下是我在eval阶段使用的config.json 和 clip_gt_arxiv路径：{ "_name_or_path": "./vicuna-7b-v1.5-16k", "architectures": [ "GraphLlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "freeze_graph_mlp_adapter": false, "graph_hidden_size": 128, "graph_select_layer": -2, "graph_tower": "clip_gt_arxiv_pub", "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 4096, "max_sequence_length": 16384, "model_type": "GraphLlama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub", "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": { "factor": 4.0, "type": "linear" }, "sep_graph_conv_front": false, "tie_word_embeddings": false, "torch_dtype": "float32", "transformers_version": "4.31.0", "tune_graph_mlp_adapter": true, "use_cache": false, "use_graph_proj": true, "use_graph_start_end": true, "vocab_size": 32003
> 
> }
> 
> ![image](https://private-user-images.githubusercontent.com/83233211/375669474-4cd191c4-24c5-4c3e-8d22-a0c01f8993cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQ3MDAsIm5iZiI6MTczMDE4NDQwMCwicGF0aCI6Ii84MzIzMzIxMS8zNzU2Njk0NzQtNGNkMTkxYzQtMjRjNS00YzNlLThkMjItYTBjMDFmODk5M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2NDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzODI2NGRmMDcwY2M3YjRmNGJiYzI2MjI4MWE1ZDhmM2U4NmU1ZDgwNTZiY2Y0ODg5MjY5YjhmMzg2Y2UxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hw8d5Aj7v1t6DPQOj0ycRqgyKoDgp96ar8FkWe-_hGo)

您好，我也遇到了同样的问题，报错内容为：

Traceback (most recent call last):
  File "./graphgpt/eval/run_graphgpt.py", line 244, in <module>
    run_eval(args, args.num_gpus)
  File "./graphgpt/eval/run_graphgpt.py", line 98, in run_eval
    ans_jsons.extend(ray.get(ans_handle))
  File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2493, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::eval_model() (pid=2040388, ip=172.16.10.18)
  File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./graphgpt/eval/run_graphgpt.py", line 120, in eval_model
    model = GraphLlamaForCausalLM.from_pretrained(args.model_name, torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True).cuda()
  File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 283, in __init__
    self.model = GraphLlamaModel(config)
  File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 99, in __init__
    clip_graph, args= load_model_pretrained(CLIP, config.pretrain_graph_model_path)
  File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 54, in load_model_pretrained
    assert osp.exists(osp.join(pretrain_model_path, 'config.json')), 'config.json missing'
AssertionError: config.json missing

`graphgpt_eval.sh`参数设置为：

output_model=/root/GraphGPT/output/stage_2/
datapath=/root/GraphGPT/graph_data/arxiv_test_instruct_cot.json
graph_data_path=/root/GraphGPT/graph_data/graph_data_all.pt
res_path=/root/GraphGPT/output/output_stage_2_arxiv_nc

我修改了`/root/GraphGPT/output/stage_2/config.json`文件的内容为

{
  "_name_or_path": "/root/vicuna-7b-v1.5-16k",
  "architectures": [
    "GraphLlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "freeze_graph_mlp_adapter": false,
  "graph_hidden_size": 128,
  "graph_select_layer": -2,
  "graph_tower": "clip_gt_arxiv",
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "max_sequence_length": 16384,
  "model_type": "GraphLlama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretrain_graph_model_path": "/root/GraphGPT/pretrained_gnn/clip_gt_arxiv",
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 4.0,
    "type": "linear"
  },
  "sep_graph_conv_front": false,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.31.0",
  "tune_graph_mlp_adapter": true,
  "use_cache": false,
  "use_graph_proj": true,
  "use_graph_start_end": true,
  "vocab_size": 32003
}
我的目录结构为`/root/GraphGPT/pretrained_gnn/clip_gt_arxiv/clip_gt_arxiv_pub.pkl`
按照您的思路修改还是不对，请问我是哪里改错了吗？

**Comment by xvrrr** [comment]
> > 我也在eval阶段遇到了这个问题，原因是config.json里的graph_tower，pretrain_graph_model_path和clip_gt_arxiv的文件路径指向不一致，通过更改文件路径解决，以下是我在eval阶段使用的config.json 和 clip_gt_arxiv路径：{ "_name_or_path": "./vicuna-7b-v1.5-16k", "architectures": [ "GraphLlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "freeze_graph_mlp_adapter": false, "graph_hidden_size": 128, "graph_select_layer": -2, "graph_tower": "clip_gt_arxiv_pub", "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 4096, "max_sequence_length": 16384, "model_type": "GraphLlama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub", "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": { "factor": 4.0, "type": "linear" }, "sep_graph_conv_front": false, "tie_word_embeddings": false, "torch_dtype": "float32", "transformers_version": "4.31.0", "tune_graph_mlp_adapter": true, "use_cache": false, "use_graph_proj": true, "use_graph_start_end": true, "vocab_size": 32003
> > }
> > ![image](https://private-user-images.githubusercontent.com/83233211/375669474-4cd191c4-24c5-4c3e-8d22-a0c01f8993cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQ3MDAsIm5iZiI6MTczMDE4NDQwMCwicGF0aCI6Ii84MzIzMzIxMS8zNzU2Njk0NzQtNGNkMTkxYzQtMjRjNS00YzNlLThkMjItYTBjMDFmODk5M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2NDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzODI2NGRmMDcwY2M3YjRmNGJiYzI2MjI4MWE1ZDhmM2U4NmU1ZDgwNTZiY2Y0ODg5MjY5YjhmMzg2Y2UxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hw8d5Aj7v1t6DPQOj0ycRqgyKoDgp96ar8FkWe-_hGo)
> 
> 您好，我也遇到了同样的问题，报错内容为：
> 
> Traceback (most recent call last): File "./graphgpt/eval/run_graphgpt.py", line 244, in run_eval(args, args.num_gpus) File "./graphgpt/eval/run_graphgpt.py", line 98, in run_eval ans_jsons.extend(ray.get(ans_handle)) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper return fn(*args, **kwargs) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper return func(*args, **kwargs) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2493, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(AssertionError): ray::eval_model() (pid=2040388, ip=172.16.10.18) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "./graphgpt/eval/run_graphgpt.py", line 120, in eval_model model = GraphLlamaForCausalLM.from_pretrained(args.model_name, torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True).cuda() File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained model = cls(config, *model_args, **model_kwargs) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 283, in **init** self.model = GraphLlamaModel(config) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 99, in **init** clip_graph, args= load_model_pretrained(CLIP, config.pretrain_graph_model_path) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 54, in load_model_pretrained assert osp.exists(osp.join(pretrain_model_path, 'config.json')), 'config.json missing' AssertionError: config.json missing
> 
> `graphgpt_eval.sh`参数设置为：
> 
> output_model=/root/GraphGPT/output/stage_2/ datapath=/root/GraphGPT/graph_data/arxiv_test_instruct_cot.json graph_data_path=/root/GraphGPT/graph_data/graph_data_all.pt res_path=/root/GraphGPT/output/output_stage_2_arxiv_nc
> 
> 我修改了`/root/GraphGPT/output/stage_2/config.json`文件的内容为
> 
> { "_name_or_path": "/root/vicuna-7b-v1.5-16k", "architectures": [ "GraphLlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "freeze_graph_mlp_adapter": false, "graph_hidden_size": 128, "graph_select_layer": -2, "graph_tower": "clip_gt_arxiv", "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 4096, "max_sequence_length": 16384, "model_type": "GraphLlama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretrain_graph_model_path": "/root/GraphGPT/pretrained_gnn/clip_gt_arxiv", "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": { "factor": 4.0, "type": "linear" }, "sep_graph_conv_front": false, "tie_word_embeddings": false, "torch_dtype": "float32", "transformers_version": "4.31.0", "tune_graph_mlp_adapter": true, "use_cache": false, "use_graph_proj": true, "use_graph_start_end": true, "vocab_size": 32003 } 我的目录结构为`/root/GraphGPT/pretrained_gnn/clip_gt_arxiv/clip_gt_arxiv_pub.pkl` 按照您的思路修改还是不对，请问我是哪里改错了吗？



![image](https://github.com/user-attachments/assets/9af79edf-52cc-4dc3-943d-684025b5279a)


您试试将GraphGPT/clip_gt_arxiv_pub 的总文件夹直接放在GraphGPT下 （clip_gt_arxiv_pub包括上图内容），不使用GraphGPT/pretrained_gnn/clip_gt_arxiv/clip_gt_arxiv_pub.pkl 这个文件路径。再将eval的config.json 里这两行设置为"pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub"；  "graph_tower": "clip_gt_arxiv_pub"

**Comment by CigarOVO** [comment]
> > > 我也在eval阶段遇到了这个问题，原因是config.json里的graph_tower，pretrain_graph_model_path和clip_gt_arxiv的文件路径指向不一致，通过更改文件路径解决，以下是我在eval阶段使用的config.json 和 clip_gt_arxiv路径：{ "_name_or_path": "./vicuna-7b-v1.5-16k", "architectures": [ "GraphLlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "freeze_graph_mlp_adapter": false, "graph_hidden_size": 128, "graph_select_layer": -2, "graph_tower": "clip_gt_arxiv_pub", "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 4096, "max_sequence_length": 16384, "model_type": "GraphLlama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub", "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": { "factor": 4.0, "type": "linear" }, "sep_graph_conv_front": false, "tie_word_embeddings": false, "torch_dtype": "float32", "transformers_version": "4.31.0", "tune_graph_mlp_adapter": true, "use_cache": false, "use_graph_proj": true, "use_graph_start_end": true, "vocab_size": 32003
> > > }
> > > ![image](https://private-user-images.githubusercontent.com/83233211/375669474-4cd191c4-24c5-4c3e-8d22-a0c01f8993cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQ3MDAsIm5iZiI6MTczMDE4NDQwMCwicGF0aCI6Ii84MzIzMzIxMS8zNzU2Njk0NzQtNGNkMTkxYzQtMjRjNS00YzNlLThkMjItYTBjMDFmODk5M2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2NDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzODI2NGRmMDcwY2M3YjRmNGJiYzI2MjI4MWE1ZDhmM2U4NmU1ZDgwNTZiY2Y0ODg5MjY5YjhmMzg2Y2UxZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hw8d5Aj7v1t6DPQOj0ycRqgyKoDgp96ar8FkWe-_hGo)
> > 
> > 
> > 您好，我也遇到了同样的问题，报错内容为：
> > Traceback (most recent call last): File "./graphgpt/eval/run_graphgpt.py", line 244, in run_eval(args, args.num_gpus) File "./graphgpt/eval/run_graphgpt.py", line 98, in run_eval ans_jsons.extend(ray.get(ans_handle)) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper return fn(*args, **kwargs) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper return func(*args, **kwargs) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2493, in get raise value.as_instanceof_cause() ray.exceptions.RayTaskError(AssertionError): ray::eval_model() (pid=2040388, ip=172.16.10.18) File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "./graphgpt/eval/run_graphgpt.py", line 120, in eval_model model = GraphLlamaForCausalLM.from_pretrained(args.model_name, torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True).cuda() File "/root/miniconda3/envs/graphgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained model = cls(config, *model_args, **model_kwargs) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 283, in **init** self.model = GraphLlamaModel(config) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 99, in **init** clip_graph, args= load_model_pretrained(CLIP, config.pretrain_graph_model_path) File "/root/GraphGPT/graphgpt/model/GraphLlama.py", line 54, in load_model_pretrained assert osp.exists(osp.join(pretrain_model_path, 'config.json')), 'config.json missing' AssertionError: config.json missing
> > `graphgpt_eval.sh`参数设置为：
> > output_model=/root/GraphGPT/output/stage_2/ datapath=/root/GraphGPT/graph_data/arxiv_test_instruct_cot.json graph_data_path=/root/GraphGPT/graph_data/graph_data_all.pt res_path=/root/GraphGPT/output/output_stage_2_arxiv_nc
> > 我修改了`/root/GraphGPT/output/stage_2/config.json`文件的内容为
> > { "_name_or_path": "/root/vicuna-7b-v1.5-16k", "architectures": [ "GraphLlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "freeze_graph_mlp_adapter": false, "graph_hidden_size": 128, "graph_select_layer": -2, "graph_tower": "clip_gt_arxiv", "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 4096, "max_sequence_length": 16384, "model_type": "GraphLlama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretrain_graph_model_path": "/root/GraphGPT/pretrained_gnn/clip_gt_arxiv", "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": { "factor": 4.0, "type": "linear" }, "sep_graph_conv_front": false, "tie_word_embeddings": false, "torch_dtype": "float32", "transformers_version": "4.31.0", "tune_graph_mlp_adapter": true, "use_cache": false, "use_graph_proj": true, "use_graph_start_end": true, "vocab_size": 32003 } 我的目录结构为`/root/GraphGPT/pretrained_gnn/clip_gt_arxiv/clip_gt_arxiv_pub.pkl` 按照您的思路修改还是不对，请问我是哪里改错了吗？
> 
> ![image](https://private-user-images.githubusercontent.com/83233211/381015732-9af79edf-52cc-4dc3-943d-684025b5279a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODYyODQsIm5iZiI6MTczMDE4NTk4NCwicGF0aCI6Ii84MzIzMzIxMS8zODEwMTU3MzItOWFmNzllZGYtNTJjYy00ZGMzLTk0M2QtNjg0MDI1YjUyNzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3MTMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNGM2ZTg4MGM5NjRlNTA4NjA0MGU3ZWQ5MmE2ZGExYzE2MDY2ZGRhZDIxNDBhNmFmMjYxY2Y2MGRjNGVjNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_VOTISwekoM_E62uoBxLpGpw8J5aaaCWSJdILFkC6o)
> 
> 您试试将GraphGPT/clip_gt_arxiv_pub 的总文件夹直接放在GraphGPT下 （clip_gt_arxiv_pub包括上图内容），不使用GraphGPT/pretrained_gnn/clip_gt_arxiv/clip_gt_arxiv_pub.pkl 这个文件路径。再将eval的config.json 里这两行设置为"pretrain_graph_model_path": "/root/autodl-tmp/GraphGPT/clip_gt_arxiv_pub"； "graph_tower": "clip_gt_arxiv_pub"

十分感谢！解决了，因为之前第一阶段训练的时候直接放入GraphGPT文件夹下报错，嵌套了一层成功了，没想到eval的时候又得改回来（；´д｀）ゞ
