### ISSUE TITLE
关于运行graphgpt_eval.sh找不到模块的问题

### ISSUE THREAD

**Issue by nulinuli** [HKUDS/GraphGPT#16]
import torch
import os
import sys
sys.path.append(u'/home/fry/桌面/GraphGPT/graphgpt')
from conversation import conv_templates, SeparatorStyle
from transformers import CLIPVisionModel, CLIPImageProcessor, StoppingCriteria
from model import *
为了找到上级目录下的模块，我用了sys.path，在修改完引用之后，运行之后又出现了其他一些找不到模块的问题，因为文件较多有点复杂不知道该怎么搞，之前把graphgpt_eval.sh以及run_graphgpt.py放在根目录里是可以运行的，但是运行一段时间后还是会有找不到模块的问题，这些文件有点复杂位置都很分散，现在不知道该如何解决了，恳请您的指点！

**Comment by nulinuli** [comment]
我已收到你的信啦！

**Comment by nulinuli** [comment]
谢谢您的答复，运行run_graphgpt.py会出现下列问题


(graphgpt) fry@fry-MS-7D90:~/GraphGPT$ sh ./scripts/eval_script/graphgpt_eval.sh
Traceback (most recent call last):
  File "./graphgpt/eval/run_graphgpt.py", line 5, in <module>
    from graphgpt.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'graphgpt'


然后我试着将run_graphgpt.py文件放在根目录下运行之后出现下列问题


(graphgpt) fry@fry-MS-7D90:~/GraphGPT$ sh ./scripts/eval_script/graphgpt_eval.sh
2023-11-10 10:05:13,195	INFO worker.py:1673 -- Started a local Ray instance.
(eval_model pid=4924) start loading
(eval_model pid=4924) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
(eval_model pid=4924) finish loading
(eval_model pid=4924) start loading
(eval_model pid=4924) Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "./run_graphgpt.py", line 240, in <module>
    run_eval(args, args.num_gpus)
  File "./run_graphgpt.py", line 94, in run_eval
    ans_jsons.extend(ray.get(ans_handle))
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AssertionError): ray::eval_model() (pid=4924, ip=172.27.37.124)
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "./run_graphgpt.py", line 116, in eval_model
    model = GraphLlamaForCausalLM.from_pretrained(args.model_name, torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True).cuda()
  File "/home/fry/.conda/envs/graphgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3085, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/fry/GraphGPT/graphgpt/model/GraphLlama.py", line 283, in __init__
    self.model = GraphLlamaModel(config)
  File "/home/fry/GraphGPT/graphgpt/model/GraphLlama.py", line 103, in __init__
    clip_graph, args= load_model_pretrained(CLIP, config.pretrain_graph_model_path)
  File "/home/fry/GraphGPT/graphgpt/model/GraphLlama.py", line 54, in load_model_pretrained
    assert osp.exists(osp.join(pretrain_model_path, 'config.json')), 'config.json missing'
AssertionError: config.json missing

再次麻烦您指点一下！

> > import torch import os import sys sys.path.append(u'/home/fry/桌面/GraphGPT/graphgpt') from conversation import conv_templates, SeparatorStyle from transformers import CLIPVisionModel, CLIPImageProcessor, StoppingCriteria from model import * 为了找到上级目录下的模块，我用了sys.path，在修改完引用之后，运行之后又出现了其他一些找不到模块的问题，因为文件较多有点复杂不知道该怎么搞，之前把graphgpt_eval.sh以及run_graphgpt.py放在根目录里是可以运行的，但是运行一段时间后还是会有找不到模块的问题，这些文件有点复杂位置都很分散，现在不知道该如何解决了，恳请您的指点！
> 
> 感谢您的反馈。graphgpt_eval.sh应该在GraphGPT的目录下运行，但不需要改变文件的位置，可以参考以下命令：
> 
> ```
> cd path/to/GraphGPT
> sh path/to/graphgpt_eval.sh
> ```

**Comment by tjb-tech** [comment]
> AssertionError: config.json missing

`AssertionError: config.json missing`的问题在于您没有将[pre-trained GNN](https://huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT)放入目录中，并使得pretrain_model_path指向pre-trained GNN

**Comment by nulinuli** [comment]
我该怎样将pretrain_model_path指向pre-trained GNN呢

(eval_model pid=8582) config: GraphLlamaConfig {
(eval_model pid=8582)   "_name_or_path": "./checkpoints/stage_2",
(eval_model pid=8582)   "architectures": [
(eval_model pid=8582)     "GraphLlamaForCausalLM"
(eval_model pid=8582)   ],
(eval_model pid=8582)   "attention_bias": false,
(eval_model pid=8582)   "bos_token_id": 1,
(eval_model pid=8582)   "eos_token_id": 2,
(eval_model pid=8582)   "freeze_graph_mlp_adapter": false,
(eval_model pid=8582)   "graph_hidden_size": 128,
(eval_model pid=8582)   "graph_select_layer": -2,
(eval_model pid=8582)   "graph_tower": "clip_gt_arxiv_pub",
(eval_model pid=8582)   "hidden_act": "silu",
(eval_model pid=8582)   "hidden_size": 4096,
(eval_model pid=8582)   "initializer_range": 0.02,
(eval_model pid=8582)   "intermediate_size": 11008,
(eval_model pid=8582)   "max_position_embeddings": 4096,
(eval_model pid=8582)   "max_sequence_length": 16384,
(eval_model pid=8582)   "model_type": "GraphLlama",
(eval_model pid=8582)   "num_attention_heads": 32,
(eval_model pid=8582)   "num_hidden_layers": 32,
(eval_model pid=8582)   "num_key_value_heads": 32,
(eval_model pid=8582)   "pad_token_id": 0,
(eval_model pid=8582)   "pretrain_graph_model_path": "/home/fry/\u684c\u9762/GraphGPT-main/checkpoints",
(eval_model pid=8582)   "pretraining_tp": 1,
(eval_model pid=8582)   "rms_norm_eps": 1e-05,
(eval_model pid=8582)   "rope_scaling": {
(eval_model pid=8582)     "factor": 4.0,
(eval_model pid=8582)     "type": "linear"
(eval_model pid=8582)   },
(eval_model pid=8582)   "rope_theta": 10000.0,
(eval_model pid=8582)   "sep_graph_conv_front": false,
(eval_model pid=8582)   "tie_word_embeddings": false,
(eval_model pid=8582)   "torch_dtype": "float32",
(eval_model pid=8582)   "transformers_version": "4.34.1",
(eval_model pid=8582)   "tune_graph_mlp_adapter": true,
(eval_model pid=8582)   "use_cache": true,
(eval_model pid=8582)   "use_graph_proj": true,
(eval_model pid=8582)   "use_graph_start_end": true,
(eval_model pid=8582)   "vocab_size": 32003
(eval_model pid=8582) }
(eval_model pid=8582) 

我的[pre-trained GNN]是在/home/fry/\u684c\u9762/GraphGPT/checkpoints/stage_2",他的路径是错误的，但是我没有找到该config文件去修改他的指向路径

**Comment by nulinuli** [comment]
我的[pre-trained GNN]是在checkpoints/stage_里面，我发现他的pretrain_graph_model_path指向如下，我并未找到该config文件，我该如何修改呢


(eval_model pid=10444) config: GraphLlamaConfig {
(eval_model pid=10444)   "_name_or_path": "./checkpoints/stage_2",
(eval_model pid=10444)   "architectures": [
(eval_model pid=10444)     "GraphLlamaForCausalLM"
(eval_model pid=10444)   ],
(eval_model pid=10444)   "attention_bias": false,
(eval_model pid=10444)   "bos_token_id": 1,
(eval_model pid=10444)   "eos_token_id": 2,
(eval_model pid=10444)   "freeze_graph_mlp_adapter": false,
(eval_model pid=10444)   "graph_hidden_size": 128,
(eval_model pid=10444)   "graph_select_layer": -2,
(eval_model pid=10444)   "graph_tower": "clip_gt_arxiv_pub",
(eval_model pid=10444)   "hidden_act": "silu",
(eval_model pid=10444)   "hidden_size": 4096,
(eval_model pid=10444)   "initializer_range": 0.02,
(eval_model pid=10444)   "intermediate_size": 11008,
(eval_model pid=10444)   "max_position_embeddings": 4096,
(eval_model pid=10444)   "max_sequence_length": 16384,
(eval_model pid=10444)   "model_type": "GraphLlama",
(eval_model pid=10444)   "num_attention_heads": 32,
(eval_model pid=10444)   "num_hidden_layers": 32,
(eval_model pid=10444)   "num_key_value_heads": 32,
(eval_model pid=10444)   "pad_token_id": 0,
(eval_model pid=10444)   "pretrain_graph_model_path": "./clip_gt_arxiv_pub",
(eval_model pid=10444)   "pretraining_tp": 1,
(eval_model pid=10444)   "rms_norm_eps": 1e-05,
(eval_model pid=10444)   "rope_scaling": {
(eval_model pid=10444)     "factor": 4.0,
(eval_model pid=10444)     "type": "linear"
(eval_model pid=10444)   },
(eval_model pid=10444)   "rope_theta": 10000.0,
(eval_model pid=10444)   "sep_graph_conv_front": false,
(eval_model pid=10444)   "tie_word_embeddings": false,
(eval_model pid=10444)   "torch_dtype": "float32",
(eval_model pid=10444)   "transformers_version": "4.34.1",
(eval_model pid=10444)   "tune_graph_mlp_adapter": true,
(eval_model pid=10444)   "use_cache": true,
(eval_model pid=10444)   "use_graph_proj": true,
(eval_model pid=10444)   "use_graph_start_end": true,
(eval_model pid=10444)   "vocab_size": 32003
(eval_model pid=10444) }
(eval_model pid=10444) 


> > AssertionError: config.json missing
> 
> `AssertionError: config.json missing`的问题在于您没有将[pre-trained GNN](https://huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT)放入目录中，并使得pretrain_model_path指向pre-trained GNN

**Comment by tjb-tech** [comment]
可以直接修改直接修改载入checkpoint的config.json文件

> 我的[pre-trained GNN]是在checkpoints/stage_里面，我发现他的pretrain_graph_model_path指向如下，我并未找到该config文件，我该如何修改呢
> 
> (eval_model pid=10444) config: GraphLlamaConfig { (eval_model pid=10444) "_name_or_path": "./checkpoints/stage_2", (eval_model pid=10444) "architectures": [ (eval_model pid=10444) "GraphLlamaForCausalLM" (eval_model pid=10444) ], (eval_model pid=10444) "attention_bias": false, (eval_model pid=10444) "bos_token_id": 1, (eval_model pid=10444) "eos_token_id": 2, (eval_model pid=10444) "freeze_graph_mlp_adapter": false, (eval_model pid=10444) "graph_hidden_size": 128, (eval_model pid=10444) "graph_select_layer": -2, (eval_model pid=10444) "graph_tower": "clip_gt_arxiv_pub", (eval_model pid=10444) "hidden_act": "silu", (eval_model pid=10444) "hidden_size": 4096, (eval_model pid=10444) "initializer_range": 0.02, (eval_model pid=10444) "intermediate_size": 11008, (eval_model pid=10444) "max_position_embeddings": 4096, (eval_model pid=10444) "max_sequence_length": 16384, (eval_model pid=10444) "model_type": "GraphLlama", (eval_model pid=10444) "num_attention_heads": 32, (eval_model pid=10444) "num_hidden_layers": 32, (eval_model pid=10444) "num_key_value_heads": 32, (eval_model pid=10444) "pad_token_id": 0, (eval_model pid=10444) "pretrain_graph_model_path": "./clip_gt_arxiv_pub", (eval_model pid=10444) "pretraining_tp": 1, (eval_model pid=10444) "rms_norm_eps": 1e-05, (eval_model pid=10444) "rope_scaling": { (eval_model pid=10444) "factor": 4.0, (eval_model pid=10444) "type": "linear" (eval_model pid=10444) }, (eval_model pid=10444) "rope_theta": 10000.0, (eval_model pid=10444) "sep_graph_conv_front": false, (eval_model pid=10444) "tie_word_embeddings": false, (eval_model pid=10444) "torch_dtype": "float32", (eval_model pid=10444) "transformers_version": "4.34.1", (eval_model pid=10444) "tune_graph_mlp_adapter": true, (eval_model pid=10444) "use_cache": true, (eval_model pid=10444) "use_graph_proj": true, (eval_model pid=10444) "use_graph_start_end": true, (eval_model pid=10444) "vocab_size": 32003 (eval_model pid=10444) } (eval_model pid=10444)
> 
> > > AssertionError: config.json missing
> > 
> > 
> > `AssertionError: config.json missing`的问题在于您没有将[pre-trained GNN](https://huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT)放入目录中，并使得pretrain_model_path指向pre-trained GNN

**Comment by nulinuli** [comment]
我已收到你的信啦！

**Comment by bamboo-boy** [comment]
您好，在执行scripts/tune_script/graphgpt_stage1.sh时，我出现了这个错误，

`Traceback (most recent call last):
  File "/share/home/gaodehong/graphgpt/code/GraphGPT/graphgpt/train/train_mem.py", line 19, in <module>
    train()
  File "/share/home/gaodehong/graphgpt/code/GraphGPT/graphgpt/train/train_graph.py", line 805, in train
    model.config.pretrain_graph_model_path = model.config.pretrain_graph_model_path + model_args.graph_tower
  File "/home/gaodehong/.conda/envs/graphgpt/lib/python3.8/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'GraphLlamaConfig' object has no attribute 'pretrain_graph_model_path'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 263921) of binary: /home/gaodehong/.conda/envs/graphgpt/bin/python
`
在config中并没有找到pretrain_graph_model_path这个属性，为此，我打印了GraphLlamaConfig为：
`GraphLlamaConfig {
  "_name_or_path": "/share/home/gaodehong/graphgpt/code/weights/vicuna-7b-v1.5",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "GraphLlama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32000
}
`
请问是为什么。

**Comment by CigarOVO** [comment]
> 我的[pre-trained GNN]是在checkpoints/stage_里面，我发现他的pretrain_graph_model_path指向如下，我并未找到该config文件，我该如何修改呢
> 
> (eval_model pid=10444) config: GraphLlamaConfig { (eval_model pid=10444) "_name_or_path": "./checkpoints/stage_2", (eval_model pid=10444) "architectures": [ (eval_model pid=10444) "GraphLlamaForCausalLM" (eval_model pid=10444) ], (eval_model pid=10444) "attention_bias": false, (eval_model pid=10444) "bos_token_id": 1, (eval_model pid=10444) "eos_token_id": 2, (eval_model pid=10444) "freeze_graph_mlp_adapter": false, (eval_model pid=10444) "graph_hidden_size": 128, (eval_model pid=10444) "graph_select_layer": -2, (eval_model pid=10444) "graph_tower": "clip_gt_arxiv_pub", (eval_model pid=10444) "hidden_act": "silu", (eval_model pid=10444) "hidden_size": 4096, (eval_model pid=10444) "initializer_range": 0.02, (eval_model pid=10444) "intermediate_size": 11008, (eval_model pid=10444) "max_position_embeddings": 4096, (eval_model pid=10444) "max_sequence_length": 16384, (eval_model pid=10444) "model_type": "GraphLlama", (eval_model pid=10444) "num_attention_heads": 32, (eval_model pid=10444) "num_hidden_layers": 32, (eval_model pid=10444) "num_key_value_heads": 32, (eval_model pid=10444) "pad_token_id": 0, (eval_model pid=10444) "pretrain_graph_model_path": "./clip_gt_arxiv_pub", (eval_model pid=10444) "pretraining_tp": 1, (eval_model pid=10444) "rms_norm_eps": 1e-05, (eval_model pid=10444) "rope_scaling": { (eval_model pid=10444) "factor": 4.0, (eval_model pid=10444) "type": "linear" (eval_model pid=10444) }, (eval_model pid=10444) "rope_theta": 10000.0, (eval_model pid=10444) "sep_graph_conv_front": false, (eval_model pid=10444) "tie_word_embeddings": false, (eval_model pid=10444) "torch_dtype": "float32", (eval_model pid=10444) "transformers_version": "4.34.1", (eval_model pid=10444) "tune_graph_mlp_adapter": true, (eval_model pid=10444) "use_cache": true, (eval_model pid=10444) "use_graph_proj": true, (eval_model pid=10444) "use_graph_start_end": true, (eval_model pid=10444) "vocab_size": 32003 (eval_model pid=10444) } (eval_model pid=10444)
> 
> > > AssertionError: config.json missing
> > 
> > 
> > `AssertionError: config.json missing`的问题在于您没有将[pre-trained GNN](https://huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT)放入目录中，并使得pretrain_model_path指向pre-trained GNN

请问是如何修改的呢？我修改二阶段checkpoint中的config.json还是报这个错误
