### ISSUE TITLE
Requesting for the code for evaluation

### ISSUE THREAD

**Issue by yzhHoward** [HKUDS/GraphGPT#19]
It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.

**Comment by tjb-tech** [comment]
> It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
The evaluation code will release by the end of this week! 
Wishing you an early Merry Christmas!

**Comment by linwhitehat** [comment]
> > It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.
> 
> Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester. The evaluation code will release by the end of this week! Wishing you an early Merry Christmas!

Hi, I'm also interested in this job and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?

**Comment by linwhitehat** [comment]
> > It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.
> 
> Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester. The evaluation code will release by the end of this week! Wishing you an early Merry Christmas!

Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?
