### ISSUE TITLE
Why are the baseline results so low?

### ISSUE THREAD

**Issue by ShuaiXuan** [HKUDS/GraphGPT#2]
hey bro！！Thank you very much for your work. I was greatly inspired after reading it. But I have a small question about the baseline result that I would like to ask you. 
I noticed you cited this article:https://arxiv.org/pdf/2305.19523.pdf. But the result of Arxiv is different from you. I see that you follow the same public division, but the GCN in this article reached 0.7182 and the SAGE reached 0.7171, while in your paper they were only 0.5267 and 0.5480 respectively. Why？
![92511698673814_ pic](https://github.com/HKUDS/GraphGPT/assets/51075031/e6e5af74-d52f-4465-b0d6-d321ea69ff14)

**Comment by tjb-tech** [comment]
Thank you very much for your attention on our GraphGPT! In our experiments, we don't use the same graph data with the paper https://arxiv.org/pdf/2305.19523.pdf. Actually, we have claimed in the Sec 4.1.2 that we encoded the raw text information using a pre-trained BERT model:
<img width="456" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/56426168/f269e42c-025a-4db4-92e1-ed58d62f25db">
While the node mapping strategy is followed by the above paper and we re-run all the baselines. In particular, you can refer to https://huggingface.co/datasets/Jiabin99/All_pyg_graph_data to find our utilized graph data. Hope that my answer is helpful for you and thank you again for the issue!

**Comment by Tebmer** [comment]
Hi, your work is really interesting. I am new to this dataset. 

I am little confused that did you ( or is it necessary to) rerun the baselines on your own data when you change the graph data in your paper? ( Looks like it's gonna be a lot of work)
