### ISSUE TITLE
Missing the code for structure-text grounding on many graphs

### ISSUE THREAD

**Issue by AGTSAAA** [HKUDS/GraphGPT#20]
Hi,

Thank you  very much for your work. Could please provide the pre-training code for structure-text grounding on large graphs such as Arxiv, as we feel only providing the checkpoint is hard to reproduce the experimental results on large graphs.

**Comment by yuh-yang** [comment]
Hi!

The codes are at [./text-graph-grounding](https://github.com/HKUDS/GraphGPT/tree/main/text-graph-grounding) and can be directly applied to Arxiv. You can refer to the example data (Cora) and prepare our released Arxiv data to match the format.
