### ISSUE TITLE
  model.get_graph_tower().to(dtype=torch.float16, device=training_args.device) AttributeError: 'str' object has no attribute 'to'

### ISSUE THREAD

**Issue by kunupup** [HKUDS/GraphGPT#21]
can you give me some advice ,thanks

**Comment by tjb-tech** [comment]
> can you give me some advice ,thanks

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
Please provide your detailed error information and we could further help you. 
Hope my answer is help for you. Wishing you an early Merry Christmas!
