### ISSUE TITLE
Would you provide the modified config.json of 'vicuna-7b-v1.5'?

### ISSUE THREAD

**Issue by xin-ran-w** [HKUDS/GraphGPT#23]
Hello, author, I try to run training stage one's code and I found the original config vicuna-7b-v1.5 lack of some config item needed in the code, such as, `pretrain_graph_model_path`. Would you provide the modified version?

**Comment by tjb-tech** [comment]
> Hello, author, I try to run training stage one's code and I found the original config vicuna-7b-v1.5 lack of some config item needed in the code, such as, `pretrain_graph_model_path`. Would you provide the modified version?

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
Please refer to #7. 
Hope my answer is help for you. Wishing you an early Merry Christmas!
