### ISSUE TITLE
Would you share your code for generating prompting files?

### ISSUE THREAD

**Issue by QiaoYRan** [HKUDS/GraphGPT#24]
Hi,
Thank you for your inspiring work. 
Would you share your code for generating those provided prompting files? I am trying to reproduce your work on different datasets, and I believe it will save me much trouble if you provided so.

**Comment by tjb-tech** [comment]
> Hi, Thank you for your inspiring work. Would you share your code for generating those provided prompting files? I am trying to reproduce your work on different datasets, and I believe it will save me much trouble if you provided so.

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
I can absolutely share the code for generating prompting files! I will prepare it and release them by the end of this week!
Wishing you an early Merry Christmas!

**Comment by QiaoYRan** [comment]
> > Hi, Thank you for your inspiring work. Would you share your code for generating those provided prompting files? I am trying to reproduce your work on different datasets, and I believe it will save me much trouble if you provided so.
> 
> Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester. I can absolutely share the code for generating prompting files! I will prepare it and release them by the end of this week! Wishing you an early Merry Christmas!

Thank you! But It seemed I failed to find the code for generating prompting files.😭Could show me the path?

**Comment by tjb-tech** [comment]
> > > Hi, Thank you for your inspiring work. Would you share your code for generating those provided prompting files? I am trying to reproduce your work on different datasets, and I believe it will save me much trouble if you provided so.
> > 
> > 
> > Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester. I can absolutely share the code for generating prompting files! I will prepare it and release them by the end of this week! Wishing you an early Merry Christmas!
> 
> Thank you! But It seemed I failed to find the code for generating prompting files.😭Could show me the path?

Sure! An example of building instruction data on Arxiv could be found at https://github.com/HKUDS/GraphGPT/blob/main/graphgpt/build_instruct_arxiv_ds.py. Hope that my answer is helpful for you.

**Comment by QiaoYRan** [comment]
> > > > Hi, Thank you for your inspiring work. Would you share your code for generating those provided prompting files? I am trying to reproduce your work on different datasets, and I believe it will save me much trouble if you provided so.
> > > 
> > > 
> > > Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester. I can absolutely share the code for generating prompting files! I will prepare it and release them by the end of this week! Wishing you an early Merry Christmas!
> > 
> > 
> > Thank you! But It seemed I failed to find the code for generating prompting files.😭Could show me the path?
> 
> Sure! An example of building instruction data on Arxiv could be found at https://github.com/HKUDS/GraphGPT/blob/main/graphgpt/build_instruct_arxiv_ds.py. Hope that my answer is helpful for you.

I really appreciate it! Wish you an early Merry Christmas too!
