### ISSUE TITLE
模型节点识别和关系推理能力

### ISSUE THREAD

**Issue by Brook-L** [HKUDS/GraphGPT#26]
请问这个模型是否具备以下能力：
1、根据论文标题或摘要中的部分文本查询到对应论文的详细信息，比如完整标题、摘要、分类
2、在不给定上下文的情况下，查询一篇论文引用的其他论文

**Comment by tjb-tech** [comment]
> 请问这个模型是否具备以下能力： 1、根据论文标题或摘要中的部分文本查询到对应论文的详细信息，比如完整标题、摘要、分类 2、在不给定上下文的情况下，查询一篇论文引用的其他论文

感谢您对我们的GraphGPT的关注。因为学校期末的课业压力，我为我的晚回复感到抱歉。
我们的模型暂时没有尝试这方面的任务。您可以尝试将我们的模型泛化到这样的任务上看下效果。我们后续也会考虑在此方向探索。希望我的回答能够帮助到您
最后提前祝您圣诞快乐！

**Comment by Brook-L** [comment]
> > 请问这个模型是否具备以下能力： 1、根据论文标题或摘要中的部分文本查询到对应论文的详细信息，比如完整标题、摘要、分类 2、在不给定上下文的情况下，查询一篇论文引用的其他论文
> 
> 感谢您对我们的GraphGPT的关注。因为学校期末的课业压力，我为我的晚回复感到抱歉。 我们的模型暂时没有尝试这方面的任务。您可以尝试将我们的模型泛化到这样的任务上看下效果。我们后续也会考虑在此方向探索。希望我的回答能够帮助到您 最后提前祝您圣诞快乐！

感谢您的回答，我正在考虑做这样的尝试，也提前祝您圣诞快乐！
