### ISSUE TITLE
Performance of LLM baselines too low

### ISSUE THREAD

**Issue by W-rudder** [HKUDS/GraphGPT#27]
Excuse me, I would like to know what are the baseline model experimental settings for LLM? Will the task template also include the title and abstract of the paper?
Here I use vicuna-7B-v1.5 for pubmed data prediction, and the ACC obtained is 0.86, which is much higher than the result in the paper.
![image](https://github.com/HKUDS/GraphGPT/assets/81093135/9d88cb47-c0f7-4e58-a78e-0b49432491df)

**Comment by tjb-tech** [comment]
Thank you very much for your interests in our work! We conduct all the experiments in the same evaluation scripts. Have you tried your evaluation scripts to evalute the model and its variants on the other datasets? We recommend you to try more experiments on the other two datasets. In our experiments, the results on pubmed are more unstable that those of the other two datasets. Hope that my answer is helpful for you.

**Comment by W-rudder** [comment]
> Thank you very much for your interests in our work! We conduct all the experiments in the same evaluation scripts. Have you tried your evaluation scripts to evalute the model and its variants on the other datasets? We recommend you to try more experiments on the other two datasets. In our experiments, the results on pubmed are more unstable that those of the other two datasets. And we change different seed and different temperature to conduct a fair experiments. One of our experimental results on pubmed is available at https://www.dropbox.com/scl/fo/n5dk2kntjsf4tzt18cnot/h?rlkey=iwtq3t7y3arhfaxrh6xkj4cgv&dl=0. You can feel free to check it. Hope that my answer is helpful for you.

Thanks for your reply!

**Comment by linwhitehat** [comment]
> Excuse me, I would like to know what are the baseline model experimental settings for LLM? Will the task template also include the title and abstract of the paper? Here I use vicuna-7B-v1.5 for pubmed data prediction, and the ACC obtained is 0.86, which is much higher than the result in the paper. ![image](https://private-user-images.githubusercontent.com/81093135/291062163-9d88cb47-c0f7-4e58-a78e-0b49432491df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjg0NjEsIm5iZiI6MTcwNTM2ODE2MSwicGF0aCI6Ii84MTA5MzEzNS8yOTEwNjIxNjMtOWQ4OGNiNDctYzBmNy00ZTU4LWE3OGUtMGI0OTQzMjQ5MWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAxMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNGQwNWRlMGViNzlkMWFlNTQwZTUwNDVkYTQ0OTAzY2ZlZGMzNWZlOWUyZWQ0OGMzZDE2NWQ1NGFmNmVkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqGE-11RJAnMRbt5EI9EXOOXdrE8N8LEPcvozglCjEk)



> Excuse me, I would like to know what are the baseline model experimental settings for LLM? Will the task template also include the title and abstract of the paper? Here I use vicuna-7B-v1.5 for pubmed data prediction, and the ACC obtained is 0.86, which is much higher than the result in the paper. ![image](https://private-user-images.githubusercontent.com/81093135/291062163-9d88cb47-c0f7-4e58-a78e-0b49432491df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNjg0NjEsIm5iZiI6MTcwNTM2ODE2MSwicGF0aCI6Ii84MTA5MzEzNS8yOTEwNjIxNjMtOWQ4OGNiNDctYzBmNy00ZTU4LWE3OGUtMGI0OTQzMjQ5MWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAxMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNGQwNWRlMGViNzlkMWFlNTQwZTUwNDVkYTQ0OTAzY2ZlZGMzNWZlOWUyZWQ0OGMzZDE2NWQ1NGFmNmVkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqGE-11RJAnMRbt5EI9EXOOXdrE8N8LEPcvozglCjEk)

May I ask in the evaluation phase, I used the [arxiv_test_instruct_cot.json](https://huggingface.co/datasets/Jiabin99/GraphGPT-eval-instruction/blob/main/arxiv_test_instruct_cot.json) data and three hours still did not end up getting the result, I would like to ask how long did you run it with what video card configuration to get this result？
