### ISSUE TITLE
关于OOM错误

### ISSUE THREAD

**Issue by bamboo-boy** [HKUDS/GraphGPT#32]
您好， 请问graphgpt_stage1.sh对应的是论文中如下图的实验部分的Stage-1-freeze还是Stage-1-tune呢？
![1](https://github.com/HKUDS/GraphGPT/assets/59140492/445d6f64-d80d-4844-be14-12f41bf74d44)
我使用4张A100，在训练时batch_size==2时出现了OOM错误，batch_size==1时可以正常训练，想请问可能是什么原因呢？

**Comment by tjb-tech** [comment]
> 您好， 请问graphgpt_stage1.sh对应的是论文中如下图的实验部分的Stage-1-freeze还是Stage-1-tune呢？ ![1](https://private-user-images.githubusercontent.com/59140492/293857811-445d6f64-d80d-4844-be14-12f41bf74d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzA4MzYsIm5iZiI6MTcwNDI3MDUzNiwicGF0aCI6Ii81OTE0MDQ5Mi8yOTM4NTc4MTEtNDQ1ZDZmNjQtZDgwZC00ODQ0LWJlMTQtMTJmNDFiZjc0ZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWNjYTU4ZjJlZDk5YjljMzUzMTM4YjgyYmJkYzg3YTFiYjQ2YTJjNDY1ZjUwMTJmYTJiNjAwYjAzMzFiMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33P3Z8pMH5u-z4KFJKz9Y_C8ghYbKgkHgUo0Ff8n-_s) 我使用4张A100，在训练时batch_size==2时出现了OOM错误，batch_size==1时可以正常训练，想请问可能是什么原因呢？

您好，请问您有用flash attention嘛

**Comment by bamboo-boy** [comment]
有使用1.0.4版本的flash atttention

**Comment by bamboo-boy** [comment]
> > 您好， 请问graphgpt_stage1.sh对应的是论文中如下图的实验部分的Stage-1-freeze还是Stage-1-tune呢？ ![1](https://private-user-images.githubusercontent.com/59140492/293857811-445d6f64-d80d-4844-be14-12f41bf74d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzA4MzYsIm5iZiI6MTcwNDI3MDUzNiwicGF0aCI6Ii81OTE0MDQ5Mi8yOTM4NTc4MTEtNDQ1ZDZmNjQtZDgwZC00ODQ0LWJlMTQtMTJmNDFiZjc0ZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA4Mjg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWNjYTU4ZjJlZDk5YjljMzUzMTM4YjgyYmJkYzg3YTFiYjQ2YTJjNDY1ZjUwMTJmYTJiNjAwYjAzMzFiMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.33P3Z8pMH5u-z4KFJKz9Y_C8ghYbKgkHgUo0Ff8n-_s) 我使用4张A100，在训练时batch_size==2时出现了OOM错误，batch_size==1时可以正常训练，想请问可能是什么原因呢？
> 
> 您好，请问您有用flash attention嘛

有使用1.0.4版本的flash atttention

**Comment by tjb-tech** [comment]
> atttention

请问是无法复现当前repos 的代码吗，还是在修改模型后发生的问题呢。目前repos中的代码是可以在单张40G A100上稳定运行的。可以检查一下是否是context length太长或者修改的模型其他部分导致参数增加。同时我们极力推荐您使用https://github.com/HKUDS/GraphGPT/tree/main/scripts/tune_script_light中的脚本，他可以显著减少训练中所需的显存。

**Comment by daixixiwang** [comment]
> > atttention
> 
> 请问是无法复现当前repos 的代码吗，还是在修改模型后发生的问题呢。目前repos中的代码是可以在单张40G A100上稳定运行的。可以检查一下是否是context length太长或者修改的模型其他部分导致参数增加。同时我们极力推荐您使用[https://github.com/HKUDS/GraphGPT/tree/main/scripts/tune_script_light中的脚本，他可以显著减少训练中所需的显存。](https://github.com/HKUDS/GraphGPT/tree/main/scripts/tune_script_light%E4%B8%AD%E7%9A%84%E8%84%9A%E6%9C%AC%EF%BC%8C%E4%BB%96%E5%8F%AF%E4%BB%A5%E6%98%BE%E8%91%97%E5%87%8F%E5%B0%91%E8%AE%AD%E7%BB%83%E4%B8%AD%E6%89%80%E9%9C%80%E7%9A%84%E6%98%BE%E5%AD%98%E3%80%82)

这个链接访问404呀
