### ISSUE TITLE
Could this model used for other Graph Custom data Finetuning

### ISSUE THREAD

**Issue by WEIYanbin1999** [HKUDS/GraphGPT#33]
If so, how should I organize the graph and place the data file where

**Comment by WEIYanbin1999** [comment]
I note your dataset looks like:
![image](https://github.com/HKUDS/GraphGPT/assets/127707751/f47c26c8-d364-4c1c-82df-face4a4dff1c)
Here the value of key "graph", show "node list" "edge index" etc. For me, it is a bit confusing, And I'd like to know where is the **graph structure**. Such as adjacent matrix or an edge list?

**Comment by serendipity800** [comment]
> I note your dataset looks like: ![image](https://private-user-images.githubusercontent.com/127707751/293966624-f47c26c8-d364-4c1c-82df-face4a4dff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzgzNzcsIm5iZiI6MTcwNDQ3ODA3NywicGF0aCI6Ii8xMjc3MDc3NTEvMjkzOTY2NjI0LWY0N2MyNmM4LWQzNjQtNGMxYy04MmRmLWZhY2U0YTRkZmYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxODA3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGEwMjdjNDgzNzM3MzMyNTQ3NDlhZDQ0ZTczYjliNWYyY2VmYTgzZDFjZDY1ZmI5ZjVhOTExYzFkMDMxYzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhL2dOtZ5Gw-FBkyaLsfKn8EjS6SQ2aJhlYeoJiXNX0) Here the value of key "graph", show "node list" "edge index" etc. For me, it is a bit confusing, And I'd like to know where is the **graph structure**. Such as adjacent matrix or an edge list?

I'm not the author, but I think that is probably some kind of PyG representation of the graph. This part(graph dict in one data point) means a subgraph of a whole graph(like arxiv). The node_idx means the id of the central node in the original graph, and edge_index is edges in the subgraph(node id starting from 0 locally), node list maps the local id of the nodes to global id in the big graph. You can see the subgraph generated by pytorch_geometric.utils.NeighborLoader. For loading the graph dataset, You can see the dataset in the training code. The training dataset will determine which "big" graph this subgraph is in and load it.

**Comment by WEIYanbin1999** [comment]
> > I note your dataset looks like: ![image](https://private-user-images.githubusercontent.com/127707751/293966624-f47c26c8-d364-4c1c-82df-face4a4dff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzgzNzcsIm5iZiI6MTcwNDQ3ODA3NywicGF0aCI6Ii8xMjc3MDc3NTEvMjkzOTY2NjI0LWY0N2MyNmM4LWQzNjQtNGMxYy04MmRmLWZhY2U0YTRkZmYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxODA3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGEwMjdjNDgzNzM3MzMyNTQ3NDlhZDQ0ZTczYjliNWYyY2VmYTgzZDFjZDY1ZmI5ZjVhOTExYzFkMDMxYzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhL2dOtZ5Gw-FBkyaLsfKn8EjS6SQ2aJhlYeoJiXNX0) Here the value of key "graph", show "node list" "edge index" etc. For me, it is a bit confusing, And I'd like to know where is the **graph structure**. Such as adjacent matrix or an edge list?
> 
> I'm not the author, but I think that is probably some kind of PyG representation of the graph. This part(graph dict in one data point) means a subgraph of a whole graph(like arxiv). The node_idx means the id of the central node in the original graph, and edge_index is edges in the subgraph(node id starting from 0 locally), node list maps the local id of the nodes to global id in the big graph. You can see the subgraph generated by pytorch_geometric.utils.NeighborLoader. For loading the graph dataset, You can see the dataset in the training code. The training dataset will determine which "big" graph this subgraph is in and load it.

Thanks for your well explanation. I understand now.

**Comment by tjb-tech** [comment]
> I'm not the author, but I think that is probably some kind of PyG representation of the graph. This part(graph dict in one data point) means a subgraph of a whole graph(like arxiv). The node_idx means the id of the central node in the original graph, and edge_index is edges in the subgraph(node id starting from 0 locally), node list maps the local id of the nodes to global id in the big graph. You can see the subgraph generated by pytorch_geometric.utils.NeighborLoader. For loading the graph dataset, You can see the dataset in the training code. The training dataset will determine which "big" graph this subgraph is in and load it.

Thanks for your nice explanation🥰

**Comment by serendipity800** [comment]
> > > I note your dataset looks like: ![image](https://private-user-images.githubusercontent.com/127707751/293966624-f47c26c8-d364-4c1c-82df-face4a4dff1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzgzNzcsIm5iZiI6MTcwNDQ3ODA3NywicGF0aCI6Ii8xMjc3MDc3NTEvMjkzOTY2NjI0LWY0N2MyNmM4LWQzNjQtNGMxYy04MmRmLWZhY2U0YTRkZmYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQxODA3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGEwMjdjNDgzNzM3MzMyNTQ3NDlhZDQ0ZTczYjliNWYyY2VmYTgzZDFjZDY1ZmI5ZjVhOTExYzFkMDMxYzdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JhL2dOtZ5Gw-FBkyaLsfKn8EjS6SQ2aJhlYeoJiXNX0) Here the value of key "graph", show "node list" "edge index" etc. For me, it is a bit confusing, And I'd like to know where is the **graph structure**. Such as adjacent matrix or an edge list?
> > 
> > 
> > I'm not the author, but I think that is probably some kind of PyG representation of the graph. This part(graph dict in one data point) means a subgraph of a whole graph(like arxiv). The node_idx means the id of the central node in the original graph, and edge_index is edges in the subgraph(node id starting from 0 locally), node list maps the local id of the nodes to global id in the big graph. You can see the subgraph generated by pytorch_geometric.utils.NeighborLoader. For loading the graph dataset, You can see the dataset in the training code. The training dataset will determine which "big" graph this subgraph is in and load it.
> 
> May I ask how to go about modifying the whole graph if you want to use the new graph data, e.g. graph_data_all.pt, the author doesn't seem to have mentioned this part of the work

你可以用torch.load打开那个graph_data_all.pt文件，里面似乎是个字典{数据集名字:pyg格式图数据}，把你的新图数据update进去就OK。然后你要生成新的instruction following数据集的时候应该是在那个id字段，比如arxiv_lp_... 第一个_前的名字和你的整图数据对上就行，数据集处理的那几个类会有相应的处理。我记的不一定准确，但大约是这样。

**Comment by linwhitehat** [comment]
> 你可以用torch.load打开那个graph_data_all.pt文件，里面似乎是个字典{数据集名字:pyg格式图数据}，把你的新图数据update进去就OK。然后你要生成新的instruction following数据集的时候应该是在那个id字段，比如arxiv_lp_... 第一个_前的名字和你的整图数据对上就行，数据集处理的那几个类会有相应的处理。我记的不一定准确，但大约是这样。

十分感谢，我也发现了这个，但是我对graph_data_all.pt的更新还有疑问，里面似乎存储的是节点特征向量，作者好像没有介绍这块是怎么生成的。

**Comment by serendipity800** [comment]
> > 你可以用torch.load打开那个graph_data_all.pt文件，里面似乎是个字典{数据集名字:pyg格式图数据}，把你的新图数据update进去就OK。然后你要生成新的instruction following数据集的时候应该是在那个id字段，比如arxiv_lp_... 第一个_前的名字和你的整图数据对上就行，数据集处理的那几个类会有相应的处理。我记的不一定准确，但大约是这样。
> 
> 十分感谢，我也发现了这个，但是我对graph_data_all.pt的更新还有疑问，里面似乎存储的是节点特征向量，作者好像没有介绍这块是怎么生成的。

我记得作者用128维的BERT编码了节点的文本信息作为初始node embeddings，你可以找一下这个仓库里另一个我提的issue，作者给了我认真的回复

**Comment by linwhitehat** [comment]
> 
> 我记得作者用128维的BERT编码了节点的文本信息作为初始node embeddings，你可以找一下这个仓库里另一个我提的issue，作者给了我认真的回复

谢谢，请问是这个 #28 里的问题吗？我看作者给了一个bert的模型
