### ISSUE TITLE
How to calculate the Accuracy and Macro-f1 from the evaluation output?

### ISSUE THREAD

**Issue by tyfeld** [HKUDS/GraphGPT#36]
Is there a script provided to calculate the acc and f1 score as is the paper in the evaluation module?
After running the evaluation script, only can we generate the output json file. 
There seems to be a lack of an ACC calculating process.

**Comment by tjb-tech** [comment]
> Is there a script provided to calculate the acc and f1 score as is the paper in the evaluation module? After running the evaluation script, only can we generate the output json file. There seems to be a lack of an ACC calculating process.

Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py

**Comment by hhy-huang** [comment]
> > Is there a script provided to calculate the acc and f1 score as is the paper in the evaluation module? After running the evaluation script, only can we generate the output json file. There seems to be a lack of an ACC calculating process.
> 
> Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py

Thank you for your response. But it seems that I can't find the file of `labelidx2arxivcategeory.csv` at line'26. I can't find it in any huggingface link.
