### ISSUE TITLE
Extract the Trained Projector

### ISSUE THREAD

**Issue by bamboo-boy** [HKUDS/GraphGPT#37]
请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。
我的一阶段训练output为：
![image](https://github.com/HKUDS/GraphGPT/assets/59140492/ad0be53a-5d73-4c7b-a1b6-de68374f1a23)

**Comment by bamboo-boy** [comment]
> 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2NzYsIm5iZiI6MTcwNDcwNTM3NiwicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYzU3ZmFhNWYzMWRhZTU3YjJmZDFiMzk0NGU2OTY5Yjk4MWI5YjA5NDVhNTQ2NDBlNDdmNDViZjYzZDg5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tvmIAE7M5OlKy6PqA5JfafJv8jvpzqPaSGEpCH7o_Jo)

s

**Comment by bamboo-boy** [comment]
> 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)

这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码
        ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu')
时出现了
  File "./scripts/extract_graph_projector.py", line 39, in <module>
    ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu')
  File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'x'.
错误，请问应该如何解决呢？

**Comment by tjb-tech** [comment]
> > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> 
> 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？

您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。

**Comment by bamboo-boy** [comment]
> > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > 
> > 
> > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？
> 
> 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。
对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件

**Comment by bamboo-boy** [comment]
> > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > 
> > 
> > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？
> 
> 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。

对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件

**Comment by tjb-tech** [comment]
> > > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > > 
> > > 
> > > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？
> > 
> > 
> > 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。
> 
> 对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件

pytorch_model.bin.index.json是output的一部分，是索引保存的不同的模型所用的。原版代码是可以正常运行的，您可以通过缩小数据和减少epoch的方式快速重新测试stage1流程，然后看下是否output中有pytorch_model.bin.index.json。有可能是之前训练的时候偶发性没有保存错误。

**Comment by bamboo-boy** [comment]
> > > > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > > > 
> > > > 
> > > > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？
> > > 
> > > 
> > > 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。
> > 
> > 
> > 对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件
> 
> pytorch_model.bin.index.json是output的一部分，是索引保存的不同的模型所用的。原版代码是可以正常运行的，您可以通过缩小数据和减少epoch的方式快速重新测试stage1流程，然后看下是否output中有pytorch_model.bin.index.json。有可能是之前训练的时候偶发性没有保存错误。

这是我一阶段所产生的output，
![image](https://github.com/HKUDS/GraphGPT/assets/59140492/eb7ba88e-6d09-4935-909f-4da3a6b4c620)
，请问其他内容与您这边是否保持一致呢，或者能否提供给我一份在您这边的原始代码上一阶段产生的output中的文件目录呢

**Comment by tjb-tech** [comment]
> 代码

您好，GraphGPT在huggingface的模型仓库就是标准的模型输出：
<img width="1267" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/56426168/2a138717-1053-4f58-affd-ea56299ed0f8">
可以看到是有pytorch_model.bin.index.json文件的。

**Comment by GoldyMoon** [comment]
你好，我想问一下最后解决了嘛

**Comment by jacklee018** [comment]
> 你好，我想问一下最后解决了嘛

from safetensors.torch import load_file

model_indices = json.load(open(os.path.join(args.model_name_or_path, 'model.safetensors.index.json')))

for ckpt_name, weight_keys in ckpt_to_key.items():
    ckpt_path = os.path.join(args.model_name_or_path, ckpt_name)
    if ckpt_name.endswith('.safetensors'):
        # 使用 safetensors 加载
        ckpt = load_file(ckpt_path)
    else:
        # 兼容非 safetensors 格式
        ckpt = torch.load(ckpt_path, map_location='cpu')
    for k in weight_keys:
        loaded_weights[k] = ckpt[k]

**Comment by lihaoran-hub** [comment]
> > > > > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory： './checkpoints/stage_1/pytorch_model.bin.index.json'。我的一阶段训练输出为：![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > > > > 
> > > > > 
> > > > > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load（os.path.join（args.model_name_or_path， ckpt_name）， map_location='cpu'） 时出现了文件 “./scripts/extract_graph_projector.py”，第 39 行，在 ckpt = torch.load（os.path.join（args.model_name_or_path， ckpt_name）， map_location='cpu'） 文件“/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py”，第 795 行，在加载返回 _legacy_load（opened_file， map_location， pickle_module，**pickle_load_args） 文件“/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py”，第 1002 行，_legacy_load magic_number = pickle_module.load（f， **pickle_load_args） _pickle。UnpicklingError：无效的加载键 'x'。错误，请问应该如何解决呢？
> > > > 
> > > > 
> > > > 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。
> > > 
> > > 
> > > 对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件
> > 
> > 
> > pytorch_model.bin.index.json是output的一部分，是索引保存的不同的模型所用的。原版代码是可以正常运行的，您可以通过缩小数据和减少epoch的方式快速重新测试stage1流程，然后看下是否output中有pytorch_model.bin.index.json。有可能是之前训练的时候偶发性没有保存错误。
> 
> 这是我一阶段所产生的output， ![image](https://github.com/HKUDS/GraphGPT/assets/59140492/eb7ba88e-6d09-4935-909f-4da3a6b4c620) ，请问其他内容与您这边是否保持一致呢，或者能否提供给我一份在您这边的原始代码上一阶段产生的output中的文件目录呢



> > > > > > 请问pytorch_model.bin.index.json是一阶段训练后的output中所应该包含的结果吗，在进行Extract the Trained Projector时，extract_projector.sh文件运行出现了错误No such file or directory: './checkpoints/stage_1/pytorch_model.bin.index.json'。 我的一阶段训练output为： ![image](https://private-user-images.githubusercontent.com/59140492/294850451-ad0be53a-5d73-4c7b-a1b6-de68374f1a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDU2OTMsIm5iZiI6MTcwNDcwNTM5MywicGF0aCI6Ii81OTE0MDQ5Mi8yOTQ4NTA0NTEtYWQwYmU1M2EtNWQ3My00YzdiLWExYjYtZGU2ODM3NGYxYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA5MTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTE0ZjE2NzQ3NjEwMGZlMTdmNDkyMDZmNTM5OWIyMGQxYTdjOWFkMDE3YjhlNGI2NGZmN2YyYTljZjU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0-GI7ejVkdXJfvlvdXCIHlKQpY7XXxSa_IAlRoE5MY)
> > > > > 
> > > > > 
> > > > > 这个问题我通过将pytorch_model.bin.index.json改为model.safetensors.index.json解决了，但是在这行代码 ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') 时出现了 File "./scripts/extract_graph_projector.py", line 39, in ckpt = torch.load(os.path.join(args.model_name_or_path, ckpt_name), map_location='cpu') File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 795, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/home/.conda/envs/graphgpt/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, 'x'. 错误，请问应该如何解决呢？
> > > > 
> > > > 
> > > > 您好，这边建议是保持原有的模型保存目录文件和extract_projector的逻辑，根据您最初的报错，是否是模型指向目录出错了。
> > > 
> > > 
> > > 对最初的报错而言，其提示没有找到pytorch_model.bin.index.json，请问该文件是一阶段训练后的output结果中的一部分吗，我在一阶段训练后的output并没有找到该文件
> > 
> > 
> > pytorch_model.bin.index.json是output的一部分，是索引保存的不同的模型所用的。原版代码是可以正常运行的，您可以通过缩小数据和减少epoch的方式快速重新测试stage1流程，然后看下是否output中有pytorch_model.bin.index.json。有可能是之前训练的时候偶发性没有保存错误。
> 
> 这是我一阶段所产生的output， ![image](https://github.com/HKUDS/GraphGPT/assets/59140492/eb7ba88e-6d09-4935-909f-4da3a6b4c620) ，请问其他内容与您这边是否保持一致呢，或者能否提供给我一份在您这边的原始代码上一阶段产生的output中的文件目录呢

我也是遇到了相同的问题，请问您是如何解决的，也是在stage1完成之后找不到pytorch_model.bin.index.json，生成的文件也是只有model.safetensors.index.json。

**Comment by lihaoran-hub** [comment]
> > 你好，我想问一下最后解决了嘛
> 
> from safetensors.torch import load_file
> 
> model_indices = json.load(open(os.path.join(args.model_name_or_path, 'model.safetensors.index.json')))
> 
> for ckpt_name, weight_keys in ckpt_to_key.items(): ckpt_path = os.path.join(args.model_name_or_path, ckpt_name) if ckpt_name.endswith('.safetensors'): # 使用 safetensors 加载 ckpt = load_file(ckpt_path) else: # 兼容非 safetensors 格式 ckpt = torch.load(ckpt_path, map_location='cpu') for k in weight_keys: loaded_weights[k] = ckpt[k]

您好，我按照您的代码进行修改，成功输出了stage_1_projector.bin，但是在运行stage2的时候报错：
experimental feature.
  graph_projector_weights = torch.load(pretrain_graph_mlp_adapter, map_location='cpu')
[rank0]: Traceback (most recent call last):
[rank0]:   File "graphgpt/train/train_mem.py", line 13, in <module>
[rank0]:     train()
[rank0]:   File "/data/lihaoran/GraphGPT-main/graphgpt/train/train_graph.py", line 870, in train
[rank0]:     model_graph_dict = model.get_model().initialize_graph_modules(
[rank0]:   File "/data/lihaoran/GraphGPT-main/graphgpt/model/GraphLlama.py", line 165, in initialize_graph_modules
[rank0]:     self.graph_projector.load_state_dict({k.split('.')[-1]: v for k, v in graph_projector_weights.items()})
[rank0]:   File "/home/lvzhiqiang/anaconda3/envs/graphgpt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for Linear:
[rank0]:        Missing key(s) in state_dict: "weight", "bias". 
/data/lihaoran/GraphGPT-main/graphgpt/model/GraphLlama.py:60: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
