### ISSUE TITLE
hugging face访问不了，能不能加一个备选的访问链接

### ISSUE THREAD

**Issue by daixixiwang** [HKUDS/GraphGPT#39]

**Comment by tjb-tech** [comment]
> _No description provided._

您好，请问是哪个huggingface链接访问不了了呢，我这边是可以正常访问的

**Comment by tjb-tech** [comment]
> _No description provided._

如果是因为网络问题，您可以通过huggingface镜像访问：https://hf-mirror.com/Jiabin99/GraphGPT-7B-mix-all （镜像原地址：https://hf-mirror.com/ ）。
当然，您可以您需要哪个具体资源的备用链接，我们也可以将其分享到百度网盘上。
