### ISSUE TITLE
The url of graph trasformer needs to be checked

### ISSUE THREAD

**Issue by wangjade54241** [HKUDS/GraphGPT#4]
Sorry to bother you...
The url of [graph transformer](https://github.com/HKUDS/GraphGPT/blob/main)  seems like the same as GraphGPT.
You mean [https://github.com/seongjunyun/Graph_Transformer_Networks] ?

**Comment by wangjade54241** [comment]
Please also check all_graph_data.pt, thanks.

**Comment by zhihui-shao** [comment]
Was LLM not fine-tuned at either stage in the paper?

**Comment by tjb-tech** [comment]
Sorry for the missing updates in the main body of README.md and we have updated the link. Actually, you can kindly refer to the table for all resources you may need in the very begining of the README.md. 
| 🤗 Huggingface Address                                        | 🎯 Description                                                |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| [huggingface.co/Jiabin99/GraphGPT-7B-mix-all](https://huggingface.co/Jiabin99/GraphGPT-7B-mix-all) | It's the checkpoint of our GraphGPT based on Vicuna-7B-v1.5 tuned on instruction data [Arxiv-PubMed-mix-NC-LP](https://huggingface.co/datasets/Jiabin99/Arxiv-PubMed-mix-NC-LP) |
| [huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT](https://huggingface.co/Jiabin99/Arxiv-PubMed-GraphCLIP-GT) | It's the checkpoint of the pre-trained graph transformer (GT) trained on Arxiv and PubMed using Text-Graph grounding. |
| [huggingface.co/datasets/Jiabin99/Arxiv-PubMed-mix-NC-LP](https://huggingface.co/datasets/Jiabin99/Arxiv-PubMed-mix-NC-LP) | This's the mixing instruction dataset with node classification (NC) and link prediction (LP) on Arxiv and PubMed. |
| [huggingface.co/datasets/Jiabin99/GraphGPT-eval-instruction](https://huggingface.co/datasets/Jiabin99/GraphGPT-eval-instruction) | We release all instruction dataset for our evaluation.       |
| [huggingface.co/datasets/Jiabin99/All_pyg_graph_data](https://huggingface.co/datasets/Jiabin99/All_pyg_graph_data) | We merge all utilized graph data.                            |
| [huggingface.co/datasets/Jiabin99/graph-matching](https://huggingface.co/datasets/Jiabin99/graph-matching) | This is the instruction data used in graph-matching stage.                            |
