### ISSUE TITLE
About baseline codes

### ISSUE THREAD

**Issue by W-rudder** [HKUDS/GraphGPT#40]
This is a very interesting project. Could you please provide some pretraining code for GNN-based baselines? Is the training process similar to common procedures? For example, is the last layer of the GNN the same as the number of categories, or does the GNN generate representations that are then used to train a separate logistic regression classifier?

Regarding the zero-shot process for the baseline, could you specify the exact configurations? For instance, ArXiv has 40 categories, and for Cora and PubMed, the number of categories is different. How should this discrepancy be handled? If possible, could you provide some example code?

Thank you for your response!

**Comment by tjb-tech** [comment]
Thanks for your interests! We claim the details of zero-shot settings of GNNs at the beginning of the Sec 4.2, which could be demonstrated as follows: 
<img width="418" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/56426168/2e58d6c5-ace4-4c16-af2b-630864da5482">
And we will consider to release codes of baselines of both supervised and zero-shot settings.

**Comment by W-rudder** [comment]
> Thanks for your interests! We claim the details of zero-shot settings of GNNs at the beginning of the Sec 4.2, which could be demonstrated as follows: <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/56426168/297262557-2e58d6c5-ace4-4c16-af2b-630864da5482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTkzMDIsIm5iZiI6MTcwNTU1OTAwMiwicGF0aCI6Ii81NjQyNjE2OC8yOTcyNjI1NTctMmU1OGQ2YzUtYWNlNC00YzE2LWFmMmItNjMwODY0ZGE1NDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNDAyYTFlMGE4OWNiOGQ3MWUyOGZmYTVhNGM0OTUyYWVlMTdjYjk4MzhkMjczYTM3OGU3ODI2OWVhM2FlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zi58e1lX8Zt2zsIVACIiDsdonsNigRt7FvErp4B2rns"> And we will consider to release codes of baselines of both supervised and zero-shot settings.

Thanks for your response!
