### ISSUE TITLE
> It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.

### ISSUE THREAD

**Issue by linwhitehat** [HKUDS/GraphGPT#41]
> It is a very nice work and inspires me a lot. How do you evaluate the predictions generated from LLM? The paper claims that evaluating with Acc and F1. However it can be hard to evaluate the text sometimes.

Thank you for your interest in our GraphGPT. I apologize for the delayed response due to the academic workload at the end of the semester.
The evaluation code will release by the end of this week! 
Wishing you an early Merry Christmas!

_Originally posted by @tjb-tech in https://github.com/HKUDS/GraphGPT/issues/19#issuecomment-1855740579_

**Comment by linwhitehat** [comment]
Hi, I'm also interested in this job and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?

**Comment by linwhitehat** [comment]
Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?

**Comment by tjb-tech** [comment]
> Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?

Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py

**Comment by linwhitehat** [comment]
> > Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?
> 
> Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py

Thank you for your reply, as I am not very familiar with this dataset, I would like to ask where to get the label information, i.e. where can I get the labelidx2arxivcategeory.csv in the code?

**Comment by tjb-tech** [comment]
> > > Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?
> > 
> > 
> > Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py
> 
> Thank you for your reply, as I am not very familiar with this dataset, I would like to ask where to get the label information, i.e. where can I get the labelidx2arxivcategeory.csv in the code?

You could refer to https://github.com/mims-harvard/GNNGuard/tree/master/Datasets/ogbn_arxiv/mapping .

**Comment by linwhitehat** [comment]
> > > > Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?
> > > 
> > > 
> > > Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py
> > 
> > 
> > Thank you for your reply, as I am not very familiar with this dataset, I would like to ask where to get the label information, i.e. where can I get the labelidx2arxivcategeory.csv in the code?
> 
> You could refer to https://github.com/mims-harvard/GNNGuard/tree/master/Datasets/ogbn_arxiv/mapping .

Thanks for your reply, I will download the label data and test it.

**Comment by Git-King-Zhan** [comment]
> > > > Hi, I'm also interested in this work and was wondering if the evaluation code you mentioned is updated? Can you clarify which part exactly?
> > > 
> > > 
> > > Thanks for your interests! An example is in https://github.com/HKUDS/GraphGPT/blob/main/scripts/eval_script/cal_metric_arxiv.py
> > 
> > 
> > Thank you for your reply, as I am not very familiar with this dataset, I would like to ask where to get the label information, i.e. where can I get the labelidx2arxivcategeory.csv in the code?
> 
> You could refer to https://github.com/mims-harvard/GNNGuard/tree/master/Datasets/ogbn_arxiv/mapping .

hello, if I use cora dataset to eval, which lable file should I use?
