### ISSUE TITLE
Ask for the construction of datasets

### ISSUE THREAD

**Issue by linwhitehat** [HKUDS/GraphGPT#42]
Hi, I'm interested in this work but I'm still not sure about the dataset construction so I would like to ask some questions about the dataset for the experimental phase.
I would like to understand how the data forms of **id**, **conversations** and **graph** are constructed when constructing the dataset for **stage1**, **stage2** and **evaluation**. I found that there is a difference in the data form used for stage1, stage2 and evaluation, is it possible to interpret the data form for the data samples of these three stages?

For example the following three samples.
1. the sample from Jiabin99/GraphGPT-eval-instruction （evaluation）
![image](https://github.com/HKUDS/GraphGPT/assets/20349381/4b551126-1c53-46d0-b587-75b83928e139)

2. the sample from Jiabin99/Arxiv-PubMed-mix-NC-LP （stage2）
![image](https://github.com/HKUDS/GraphGPT/assets/20349381/577db541-f243-4f53-a374-26cb55c00f0a)

3. the sample from Jiabin99/graph-matching （stage1）
![image](https://github.com/HKUDS/GraphGPT/assets/20349381/8ea732da-9b03-4e12-9bce-e37b33098b52)

**Comment by linwhitehat** [comment]
This is great work and I am interested in it! But when I want to use gpt-3.5 to generate the answer based on the graph-match example, I found that the input of the graph does not contain the title and summary information in the node as stated in the prompt, I hope the author will help me to solve how to generate the answer using gpt?

**Comment by linwhitehat** [comment]
Forgive me if I am not very familiar with this dataset and would like to ask how you constructed all_pyg_graph_data.pt?
The work is really interesting and also I would like to know if this work can be applied to graph level categorization as well?

**Comment by tjb-tech** [comment]
> This is great work and I am interested in it! But when I want to use gpt-3.5 to generate the answer based on the graph-match example, I found that the input of the graph does not contain the title and summary information in the node as stated in the prompt, I hope the author will help me to solve how to generate the answer using gpt?

Hi, sorry for the late reply due to several conference ddl last few months. Actually, we only use CoT distillation to generate the instruction in the stage 2 (downstream tasks). So you don't need to let GPT-3.5 to conduct answer on graph-matching (stage 1).

**Comment by tjb-tech** [comment]
> Forgive me if I am not very familiar with this dataset and would like to ask how you constructed all_pyg_graph_data.pt? The work is really interesting and also I would like to know if this work can be applied to graph level categorization as well?

Thanks for your interests! You can put all pyg Data in a `dict`  and save the dict into the `.pt` format. As for the graph level categorization, you can try it!
