### ISSUE TITLE
The error occurred while installing the packages listed in requirements.txt.

### ISSUE THREAD

**Issue by TrendBoyedc** [HKUDS/GraphGPT#45]
My mirror channels is as follows.
channels:
  - default
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
The error occurred while installing the packages listed in requirements.txt:
![1705676842671](https://github.com/HKUDS/GraphGPT/assets/49978591/b4b2d516-05e0-4f8e-a46b-3ec79c450c1c)

**Comment by LouHerGetUp** [comment]
Hello, I also have a similar problem, have you solved it?

**Comment by tjb-tech** [comment]
Please refer to the issue #9

**Comment by tjb-tech** [comment]
> My mirror channels is as follows. channels:
> 
> * default
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/fastai/
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
>   The error occurred while installing the packages listed in requirements.txt:
>   ![1705676842671](https://private-user-images.githubusercontent.com/49978591/298108985-b4b2d516-05e0-4f8e-a46b-3ec79c450c1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjM3MjAsIm5iZiI6MTcxMDgyMzQyMCwicGF0aCI6Ii80OTk3ODU5MS8yOTgxMDg5ODUtYjRiMmQ1MTYtMDVlMC00ZjhlLWE0NmItM2VjNzljNDUwYzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA0NDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMWE1YmRmNGM5NTc0NmY0MmZlYWE5NzBiOWFkZWFlZGViNjAzYmNmMjQ3MGViYjA4MDIyZjI0NzNkNGJlZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.npWrRiWea7gsrFNVkbv1_fdjV_A1M3DdQ-seyJW0Pjg)

Please refer to the issue #9
