### ISSUE TITLE
ModuleNotFoundError: No module named 'graphgpt'

### ISSUE THREAD

**Issue by lhkhiem28** [HKUDS/GraphGPT#47]
ModuleNotFoundError: No module named 'graphgpt' when runing sh ./scripts/tune_script/graphgpt_stage1.sh

```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
    from graphgpt.train.llama_flash_attn_monkey_patch import (
ModuleNotFoundError:     No module named 'graphgpt'from graphgpt.train.llama_flash_attn_monkey_patch import (

ModuleNotFoundError: No module named 'graphgpt'
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
    from graphgpt.train.llama_flash_attn_monkey_patch import (
ModuleNotFoundError: No module named 'graphgpt'
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
    from graphgpt.train.llama_flash_attn_monkey_patch import (
ModuleNotFoundError: No module named 'graphgpt'
[2024-02-13 15:35:41,869] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1123051) of binary: /afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/bin/python
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
    main()
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
graphgpt/train/train_mem.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-13_15:35:41
  host      : qa-a100-002.crc.nd.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1123052)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-02-13_15:35:41
  host      : qa-a100-002.crc.nd.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1123053)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-02-13_15:35:41
  host      : qa-a100-002.crc.nd.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1123054)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-13_15:35:41
  host      : qa-a100-002.crc.nd.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1123051)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Melo-1017** [comment]
I meet the same problem. Has it been resolved?

**Comment by tjb-tech** [comment]
> ModuleNotFoundError: No module named 'graphgpt' when runing sh ./scripts/tune_script/graphgpt_stage1.sh
> 
> ```
> Traceback (most recent call last):
>   File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
> Traceback (most recent call last):
>   File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
>     from graphgpt.train.llama_flash_attn_monkey_patch import (
> ModuleNotFoundError:     No module named 'graphgpt'from graphgpt.train.llama_flash_attn_monkey_patch import (
> 
> ModuleNotFoundError: No module named 'graphgpt'
> Traceback (most recent call last):
>   File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
>     from graphgpt.train.llama_flash_attn_monkey_patch import (
> ModuleNotFoundError: No module named 'graphgpt'
> Traceback (most recent call last):
>   File "/afs/crc.nd.edu/user/k/kle3/DIAL-Lab/GraphGPT/graphgpt/train/train_mem.py", line 4, in <module>
>     from graphgpt.train.llama_flash_attn_monkey_patch import (
> ModuleNotFoundError: No module named 'graphgpt'
> [2024-02-13 15:35:41,869] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1123051) of binary: /afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/bin/python
> Traceback (most recent call last):
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 810, in <module>
>     main()
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
>     return f(*args, **kwargs)
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
>     run(args)
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
>     elastic_launch(
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/afs/crc.nd.edu/user/k/kle3/.conda/envs/GraphGPT/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> graphgpt/train/train_mem.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2024-02-13_15:35:41
>   host      : qa-a100-002.crc.nd.edu
>   rank      : 1 (local_rank: 1)
>   exitcode  : 1 (pid: 1123052)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [2]:
>   time      : 2024-02-13_15:35:41
>   host      : qa-a100-002.crc.nd.edu
>   rank      : 2 (local_rank: 2)
>   exitcode  : 1 (pid: 1123053)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [3]:
>   time      : 2024-02-13_15:35:41
>   host      : qa-a100-002.crc.nd.edu
>   rank      : 3 (local_rank: 3)
>   exitcode  : 1 (pid: 1123054)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2024-02-13_15:35:41
>   host      : qa-a100-002.crc.nd.edu
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 1123051)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

Hello, all shell files need to be run directly under the ./GraphGPT directory. Specifically, before running, please first run `cd /path/to/GraphGPT`
