### ISSUE TITLE
这个预训练模型可以用来做图结构的下游预测任务么？有相关示例么？

### ISSUE THREAD

**Issue by dlmty** [HKUDS/GraphGPT#48]
这个预训练模型可以用来做图结构的下游预测任务么？有相关示例么？

**Comment by tjb-tech** [comment]
> 这个预训练模型可以用来做图结构的下游预测任务么？有相关示例么？

您好，感谢您的提问，GraphGPT项目起初没有考虑图结构学习任务，但是您可以关注我们组后续在图结构学习和LLM结合的工作GraphEdit，其专门针对图结构学习进行了优化设计
