### ISSUE TITLE
The results of baselines are not reasonable and not correct (Clarified by author)

### ISSUE THREAD

**Issue by AGTSAAA** [HKUDS/GraphGPT#52]
For the ogbn-Arxiv supervised setting, the results of GCN, Graphsage, and other GNN methods on ogbn-arxiv should be higher than 70. This is well-known in the community. 

<img width="460" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/83741666/91393be2-ff6d-46b5-b675-88ab628aa061">

**Comment by tjb-tech** [comment]
> For the ogbn-Arxiv supervised setting, the results of GCN, Graphsage, and other GNN methods on ogbn-arxiv should be higher than 70. This is well-known in the community.
> 
> <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/83741666/316277513-91393be2-ff6d-46b5-b675-88ab628aa061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTYwNzgsIm5iZiI6MTcxMTI1NTc3OCwicGF0aCI6Ii84Mzc0MTY2Ni8zMTYyNzc1MTMtOTEzOTNiZTItZmY2ZC00NmI1LWI2NzUtODhhYjYyOGFhMDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA0NDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YWZlOTJjYTU5NGQ2NzAwZmFmODIyZmJlM2MzNzUxNDg0YjA2ODQzMWQzNzU0NjljOGY5Nzg4YWM4ZmE1MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGoUmo6mt_guNuM6KCtEdfYPSyXCRvbNIxHA5QCcx_Q">

Hi, we have reply this issue in the issue #2 . Please refer to that issue.

**Comment by tjb-tech** [comment]
> Learning

BERT have many versions of models. We use this version https://huggingface.co/google/bert_uncased_L-2_H-128_A-2.

**Comment by tjb-tech** [comment]
> Thank you for your reply.
> 
> 1. I still believe that even with the used BERT, the performance would not be so low. I will check this by running the code in [1,2].
> 2. If GNNs with other BERT models in [1,2] can outperform your methods, how can we say GraphGPT can beat simple GNNs?
> 
> [1] SimTG: A Frustratingly Simple Approach For Textual Graph Representation Learning. [2] Exploring the Potential of Large Language Models (LLMs) in Learning on Graphs.

We use the same node features processed by the same bert model https://huggingface.co/google/bert_uncased_L-2_H-128_A-2 into baselines and our GraphGPT. So the comparisons are fair and it's only the case of initial node features. The methods you mentioned tends to enhance the node representations use language models or others. The bert models they used may be more powerful than ours. But it's only different data pre-processing and initial experimental settings. You could use our data to run the baselines like GAT, GCN ... to verify our experiments. Btw, the results could further prove that our GraphGPT are not that sensitive to the quality of node features than traditional GNNs.

**Comment by tjb-tech** [comment]
> This is not the case. Your input for GraphGPT also includes the abstract and title, i.e., raw text .
> 
> For fairness, one can actually use any BERT model to embed this raw text for GNN. If we input the raw text into GNN, we can achieve an accuracy higher than 70%

Thanks for your questions. But traditional GNNs could not directly leverage raw text into them. They could only leverage node features. GraphGPT could leverage the raw text because the superiority of LLMs.

**Comment by tjb-tech** [comment]
> a

Thanks for your questions. We'd like to clarify that we use the same node features into both baseline GNNs and GraphGPT and in this academic experiment, it's the commonly used control variable method to validate the effectiveness of the model architecture. In our experiments, we keep the **same data-preprocessing**, i.e., the same node features **all the time**.

**Comment by tjb-tech** [comment]
> is

Thanks for your question! But actually, in Language is All a Graph Needs, it leverage Skip-gram **rather than** bag-of-words for arxiv. 
<img width="642" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/56426168/88e5c702-35a5-4c2a-94d6-423925da2880">
And refer to original OGB website, thay run the skip-gram model over the MAG corpus. So **skip-gram requires training** but we use the **pre-trained BERT (that is training-free)** for data pre-processing. So to some extent, the features of the OGBN-ARXIV are optimized for MAG corpus.
<img width="1169" alt="image" src="https://github.com/HKUDS/GraphGPT/assets/56426168/f06dd6a4-60fc-4daa-b1ed-df700596e321">
And we clarify again that our experiments are fair and reasonable enough because we use the same node features **all the time**.

**Comment by tjb-tech** [comment]
> Thank you for your reply.
> 
> But you chose a very weak BERT model for GNN. Could you explain why you didn't choose the BERT methods that were widely used in previous work? My point is that you utilize raw text for GraphGPT. Thus, we can actually utilize any pre-trained BERT model (which are all training-free) for GNN.
> 
> <img alt="image" width="749" src="https://private-user-images.githubusercontent.com/83741666/316314524-85a9394e-5e1e-4e35-8b38-82111ca71dc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk4MDIsIm5iZiI6MTcxMTI4OTUwMiwicGF0aCI6Ii84Mzc0MTY2Ni8zMTYzMTQ1MjQtODVhOTM5NGUtNWUxZS00ZTM1LThiMzgtODIxMTFjYTcxZGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMWUyMGZlMDhiM2UwYzMwOTk4YjZkMmRmODYzMWMwYjI4YzE3MWEyZDkyZDNmMmYwNGE5ODk2YjFlZmY2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mlkd9kMGGUbhsS79ldQne6lniwWhHcXJx9vJbpYLv7c"> <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/83741666/316314597-785ba492-aef5-49b7-91a7-e67eb41a74f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk4MDIsIm5iZiI6MTcxMTI4OTUwMiwicGF0aCI6Ii84Mzc0MTY2Ni8zMTYzMTQ1OTctNzg1YmE0OTItYWVmNS00OWI3LTkxYTctZTY3ZWI0MWE3NGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZDUwOGI4ZDlkZGIzNWJmY2U3YTgwNjFiOTlmNTdkNDA5NzhiNzRiOWY3MmY0NWY2YjNiZDEyNTdmOTEyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2y3gNBUFc5DYjyD52oHJ3qgXGdeFzU-rNP_H8p0UQCQ">

Thanks for your questions! The original reason why we choose this model is very straightforward. Because we want keep the same dimension of our data (i.e. 128) with original ogb data. Most dimensions of features you mentioned above are 768. So the acc are higher is understandable.

**Comment by nowyouseemejoe** [comment]
@tjb-tech You still haven’t answered @AGTSAAA  ’s question about why you’re using a weaker BERT model for GNNs. In my experiments, a GNN with a ‘standard’ BERT can achieve much better performance than you reported. You reported significantly lower performance for the GNN baselines, so how can you claim your model has a ‘significant’ improvement over GNNs?
