### ISSUE TITLE
Some questions about input embedding of graph tokens

### ISSUE THREAD

**Issue by brothermaster** [HKUDS/GraphGPT#53]
All input embeddings were trained in the "initialize_graph_tokenizer" method at Self-Supervised Instruction Tuning stage , but only "-num_new_token" were loaded in Task-Specific Instruction Tuning stage while embedding of other tokens are not used.
Question 1: Why don't you use all embeddings that were trained?  
Question 2: Actually, embeddings of "num_new_token" of graph are not input into LLM.Text embeddings and aligned graph representation are concatenated and input into LLM. Why do you train graph tokens?

**Comment by zhuiyue233** [comment]
> All input embeddings were trained in the "initialize_graph_tokenizer" method at Self-Supervised Instruction Tuning stage , but only "-num_new_token" were loaded in Task-Specific Instruction Tuning stage while embedding of other tokens are not used. Question 1: Why don't you use all embeddings that were trained? Question 2: Actually, embeddings of "num_new_token" of graph are not input into LLM.Text embeddings and aligned graph representation are concatenated and input into LLM. Why do you train graph tokens?

您好，我想请问一下，您知道Graph token是怎么得到的么

**Comment by brothermaster** [comment]
> > All input embeddings were trained in the "initialize_graph_tokenizer" method at Self-Supervised Instruction Tuning stage , but only "-num_new_token" were loaded in Task-Specific Instruction Tuning stage while embedding of other tokens are not used. Question 1: Why don't you use all embeddings that were trained? Question 2: Actually, embeddings of "num_new_token" of graph are not input into LLM.Text embeddings and aligned graph representation are concatenated and input into LLM. Why do you train graph tokens?
> 
> 您好，我想请问一下，您知道Graph token是怎么得到的么

在这个位置：https://github.com/HKUDS/GraphGPT/blob/3001b031c084845ac9a255a98ae6e680beaed41a/graphgpt/model/GraphLlama.py#L390

**Comment by zhuiyue233** [comment]
> > > All input embeddings were trained in the "initialize_graph_tokenizer" method at Self-Supervised Instruction Tuning stage , but only "-num_new_token" were loaded in Task-Specific Instruction Tuning stage while embedding of other tokens are not used. Question 1: Why don't you use all embeddings that were trained? Question 2: Actually, embeddings of "num_new_token" of graph are not input into LLM.Text embeddings and aligned graph representation are concatenated and input into LLM. Why do you train graph tokens?
> > 
> > 
> > 您好，我想请问一下，您知道Graph token是怎么得到的么
> 
> 在这个位置：
> 
> https://github.com/HKUDS/GraphGPT/blob/3001b031c084845ac9a255a98ae6e680beaed41a/graphgpt/model/GraphLlama.py#L390

好诶，感谢！
