### ISSUE TITLE
GNN Baseline Too Low

### ISSUE THREAD

**Issue by W-rudder** [HKUDS/GraphGPT#65]
Hello! I think this is a very interesting work! However, is the GNN result given in the paper too low? Following the proposal in Section 4.2 of the paper, 
![image](https://github.com/HKUDS/GraphGPT/assets/81093135/0b66c498-6a96-4674-9e29-669126fb92bd)
I trained a GNN and a single-layer linear classifier using the arXiv training dataset and. When testing on the PubMed/Cora dataset, I trained a new classifier using the training set of the target dataset, while keeping the parameters of the GNN fixed. In the end, I obtained the following results, which differ significantly from those presented in the paper. Could it be due to differences in my experimental setup compared to that of the paper? What should be the correct experimental setup? The paper does not seem to provide detailed descriptions. Looking forward to your reply! Wishing you smooth work and a pleasant life!
![image](https://github.com/HKUDS/GraphGPT/assets/81093135/35768694-3132-499a-b0b9-1ac0d05f7f83)

**Comment by tjb-tech** [comment]
> Hello! I think this is a very interesting work! However, is the GNN result given in the paper too low? Following the proposal in Section 4.2 of the paper, ![image](https://private-user-images.githubusercontent.com/81093135/326407069-0b66c498-6a96-4674-9e29-669126fb92bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDcwNjktMGI2NmM0OTgtNmE5Ni00Njc0LTllMjktNjY5MTI2ZmI5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZGJlZDE2ODNhMzhjOWU5ZWI5MjRmN2NhYjY0MzczOWIyMjk3Zjg0ZGY1ZTQzZjkxNzViNGExOWE0YjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6s-ut96OJe5DMwi_nt1Uco2iIp59QtKufPw7nMrXYpo) I trained a GNN and a single-layer linear classifier using the arXiv training dataset and. When testing on the PubMed/Cora dataset, I trained a new classifier using the training set of the target dataset, while keeping the parameters of the GNN fixed. In the end, I obtained the following results, which differ significantly from those presented in the paper. Could it be due to differences in my experimental setup compared to that of the paper? What should be the correct experimental setup? The paper does not seem to provide detailed descriptions. Looking forward to your reply! Wishing you smooth work and a pleasant life! ![image](https://private-user-images.githubusercontent.com/81093135/326408456-35768694-3132-499a-b0b9-1ac0d05f7f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDg0NTYtMzU3Njg2OTQtMzEzMi00OTlhLWIwYjktMWFjMGQwNWY3ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjY4YzFmOWNmODA1MzU0M2M1M2JkNjhjODFhNmE2YjgyNWFmODhkMzU2NmZjMWM5ZWY0ZDRhY2E1MjY2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ExkBTPITVdC5tp1dQt1H0QbG_FpfzNrx8T7uRHN-DEY)

Thanks for your interests! Actually, the zero-shot settings in our experiments are not required to be trained. Taking arxiv to pubmed setting as an example, we use the GNN backbone trained on arxiv, and the classifier head in the the same GNN backbone+head model trained on pubmed to conduct training-free zero-shot setting. We think that your operation training classifier head in new dataset is more like domain adaption rather than zero-shot learning.

**Comment by W-rudder** [comment]
> > Hello! I think this is a very interesting work! However, is the GNN result given in the paper too low? Following the proposal in Section 4.2 of the paper, ![image](https://private-user-images.githubusercontent.com/81093135/326407069-0b66c498-6a96-4674-9e29-669126fb92bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDcwNjktMGI2NmM0OTgtNmE5Ni00Njc0LTllMjktNjY5MTI2ZmI5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZGJlZDE2ODNhMzhjOWU5ZWI5MjRmN2NhYjY0MzczOWIyMjk3Zjg0ZGY1ZTQzZjkxNzViNGExOWE0YjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6s-ut96OJe5DMwi_nt1Uco2iIp59QtKufPw7nMrXYpo) I trained a GNN and a single-layer linear classifier using the arXiv training dataset and. When testing on the PubMed/Cora dataset, I trained a new classifier using the training set of the target dataset, while keeping the parameters of the GNN fixed. In the end, I obtained the following results, which differ significantly from those presented in the paper. Could it be due to differences in my experimental setup compared to that of the paper? What should be the correct experimental setup? The paper does not seem to provide detailed descriptions. Looking forward to your reply! Wishing you smooth work and a pleasant life! ![image](https://private-user-images.githubusercontent.com/81093135/326408456-35768694-3132-499a-b0b9-1ac0d05f7f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDg0NTYtMzU3Njg2OTQtMzEzMi00OTlhLWIwYjktMWFjMGQwNWY3ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjY4YzFmOWNmODA1MzU0M2M1M2JkNjhjODFhNmE2YjgyNWFmODhkMzU2NmZjMWM5ZWY0ZDRhY2E1MjY2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ExkBTPITVdC5tp1dQt1H0QbG_FpfzNrx8T7uRHN-DEY)
> 
> Thanks for your interests! Actually, the zero-shot settings in our experiments are not required to be trained. Taking arxiv to pubmed setting as an example, we use the GNN backbone trained on arxiv, and the classifier head in the the same GNN backbone+head model trained on pubmed to conduct training-free zero-shot setting. We think that your operation training classifier head in new dataset is more like domain adaption rather than zero-shot learning.


Thank you for your prompt reply! But I'm sorry I may be a little uncertain about what you mean. Are you saying that we use the classifier from GNN+classifier trained on PubMed and the GNN from GNN+classifier trained on arXiv for zero-shot learning, right?

**Comment by tjb-tech** [comment]
> > > Hello! I think this is a very interesting work! However, is the GNN result given in the paper too low? Following the proposal in Section 4.2 of the paper, ![image](https://private-user-images.githubusercontent.com/81093135/326407069-0b66c498-6a96-4674-9e29-669126fb92bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDcwNjktMGI2NmM0OTgtNmE5Ni00Njc0LTllMjktNjY5MTI2ZmI5MmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZGJlZDE2ODNhMzhjOWU5ZWI5MjRmN2NhYjY0MzczOWIyMjk3Zjg0ZGY1ZTQzZjkxNzViNGExOWE0YjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6s-ut96OJe5DMwi_nt1Uco2iIp59QtKufPw7nMrXYpo) I trained a GNN and a single-layer linear classifier using the arXiv training dataset and. When testing on the PubMed/Cora dataset, I trained a new classifier using the training set of the target dataset, while keeping the parameters of the GNN fixed. In the end, I obtained the following results, which differ significantly from those presented in the paper. Could it be due to differences in my experimental setup compared to that of the paper? What should be the correct experimental setup? The paper does not seem to provide detailed descriptions. Looking forward to your reply! Wishing you smooth work and a pleasant life! ![image](https://private-user-images.githubusercontent.com/81093135/326408456-35768694-3132-499a-b0b9-1ac0d05f7f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTA4OTIsIm5iZiI6MTcxNDM5MDU5MiwicGF0aCI6Ii84MTA5MzEzNS8zMjY0MDg0NTYtMzU3Njg2OTQtMzEzMi00OTlhLWIwYjktMWFjMGQwNWY3ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMjY4YzFmOWNmODA1MzU0M2M1M2JkNjhjODFhNmE2YjgyNWFmODhkMzU2NmZjMWM5ZWY0ZDRhY2E1MjY2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ExkBTPITVdC5tp1dQt1H0QbG_FpfzNrx8T7uRHN-DEY)
> > 
> > 
> > Thanks for your interests! Actually, the zero-shot settings in our experiments are not required to be trained. Taking arxiv to pubmed setting as an example, we use the GNN backbone trained on arxiv, and the classifier head in the the same GNN backbone+head model trained on pubmed to conduct training-free zero-shot setting. We think that your operation training classifier head in new dataset is more like domain adaption rather than zero-shot learning.
> 
> Thank you for your prompt reply! But I'm sorry I may be a little uncertain about what you mean. Are you saying that we use the classifier from GNN+classifier trained on PubMed and the GNN from GNN+classifier trained on arXiv for zero-shot learning, right?

Yes, you are right.
