### ISSUE TITLE
How to evaluate the link prediction performance of GraphGPT

### ISSUE THREAD

**Issue by Ashley0703** [HKUDS/GraphGPT#66]
Hi,

Thank you for sharing your fantastic work. I recently want to reproduce the link prediction evaluation part. In your paper, you mentioned that 

"we utilize three commonly adopted evaluation metrics: Accuracy and Macro F1 for node
classification, and AUC (Area Under the Curve) for link prediction". 

I can find from the example files for node classification evaluation but I can't find how to use the evaluation output to calculate the AUC.

What confuses most is that AUC requires the confidence of existence of links between 2 nodes. However, in your prompt design, you only ask llm for whether there's a link or not which means you can only get 0 or 1.

I would be appreciate it if you could provide me with further explanation. Thank you for your time!

**Comment by tjb-tech** [comment]
> explanation

Thanks for your interests in our GraphGPT. We treat link prediction as a binary classification problem on the edges (linking or not linking). We set the output of 'yes' as 1 and 'no' as 0, and then proceed to calculate the AUC (Area Under the Curve). Specifically, we utilize the computation function provided by sklearn to perform the calculation directly.

**Comment by Ashley0703** [comment]
Thank you for your clarification!
