### ISSUE TITLE
Requesting for the code for structure-text grounding

### ISSUE THREAD

**Issue by SpaceLearner** [HKUDS/GraphGPT#8]
It is a very nice work and inspires me a lot. Do you have plan to release the code for the structure-text grounding part ?

**Comment by tjb-tech** [comment]
Thank you for your attention on our GraphGPT! We will prepare the code for the structure-text grounding part this week and release it in the same github repo. Hope that my answer will be helpful for you and thank you again for your supports!

**Comment by SpaceLearner** [comment]
Thanks a lot!
