### ISSUE TITLE
在使用graphgpt的checkpoints推理时报错“Cannot copy out of meta tensor; no data!”

### ISSUE THREAD

**Issue by wmx0708** [HKUDS/GraphGPT#80]
跑graphgpt_eval.sh时，sh文件配置如下，stage_1中放置的是pytorch_model-00001-of-00003.bin文件和相关huggingface上的配置文件
![image](https://github.com/user-attachments/assets/cbda9769-a93b-405a-a413-842fe7208462)
结果在加载模型到cuda的时候，报错“NotImplementedError: Cannot copy out of meta tensor; no data!”
![image](https://github.com/user-attachments/assets/a05005bf-ece5-4df4-be74-41c54e746bb8)
运行时一直warning "copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)”
![image](https://github.com/user-attachments/assets/551b7ab5-db3e-46c1-a1bb-5e64a192628c)
且提示模型初始化参数问题
![image](https://github.com/user-attachments/assets/9c225cf9-29fb-4bc8-b6af-5e54c07ffa45)
请问是否是我在运行eval时的配置存在问题

**Comment by lyinguo** [comment]
请问这个怎么进行解决的哇，方便回答一下吗
