### ISSUE TITLE
  The user requested protobuf==3.20.0     icetk 0.0.7 depends on protobuf<3.19

### ISSUE THREAD

**Issue by kunupup** [HKUDS/GraphGPT#9]
environment error

**Comment by tjb-tech** [comment]
Please just install protobuf==3.20.0 and ignore the icetk 0.0.7. Feel free to ask us if you still have some error!

**Comment by kunupup** [comment]
I have many problems with the environment, can you give me some advice?




王坤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HKUDS/GraphGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HKUDS/GraphGPT]   The user requested protobuf==3.20.0     icetk 0.0.7 depends on protobuf<3.19 (Issue #9)





 
Please just install protobuf==3.20.0 and ignore the icetk 0.0.7. Feel free to ask us if you still have some error!

**Comment by tjb-tech** [comment]
Sorry to hear that and just feel free to post your problems in the issue. We will try our best to deal with it.

**Comment by kunupup** [comment]
ERROR: No matching distribution found for pyg-lib==0.2.0

**Comment by kunupup** [comment]
can i ignore pyg-lib?

**Comment by kunupup** [comment]
ERROR: No matching distribution found for PyGObject==3.26.1
ERROR: No matching distribution found for python-apt==1.6.5+ubuntu0.7
ERROR: No matching distribution found for unattended-upgrades==0.1

**Comment by tjb-tech** [comment]
> ERROR: No matching distribution found for PyGObject==3.26.1 ERROR: No matching distribution found for python-apt==1.6.5+ubuntu0.7 ERROR: No matching distribution found for unattended-upgrades==0.1

Maybe you could ignore this packages and directly run the model.

**Comment by kunupup** [comment]
ERROR: Cannot install -r requirements.txt (line 148), -r requirements.txt (line 171), -r requirements.txt (line 173) and protobuf==3.20.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested protobuf==3.20.0
    ray 2.6.1 depends on protobuf!=3.19.5 and >=3.15.3
    tensorboard 2.13.0 depends on protobuf>=3.19.6
But there are too many errors, how do i should do, thanks for your patience

**Comment by 123THU** [comment]
@kunupup hi, I encountered the same problem about PyGObject, have you solved this problem? :)

**Comment by 123THU** [comment]
> [@kunupup](https://github.com/kunupup) hi, I encountered the same problem about PyGObject, have you solved this problem? :)
solved it, use this to install [pygobject:3.26.1](https://launchpad.net/ubuntu/+source/pygobject/3.26.1-2)

**Comment by Git-King-Zhan** [comment]
> > [@kunupup](https://github.com/kunupup) hi, I encountered the same problem about PyGObject, have you solved this problem? :)
> > solved it, use this to install [pygobject:3.26.1](https://launchpad.net/ubuntu/+source/pygobject/3.26.1-2)

have you solved it？

**Comment by 123THU** [comment]
> > > [@kunupup](https://github.com/kunupup) hi, I encountered the same problem about PyGObject, have you solved this problem? :)
> > > solved it, use this to install [pygobject:3.26.1](https://launchpad.net/ubuntu/+source/pygobject/3.26.1-2)
> 
> have you solved it？

yes, use the link I provided to install.
